---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Un conector es el software de NetApp que se ejecuta en su red de cloud o en las instalaciones. Ejecuta las acciones que BlueXP necesita realizar para gestionar su infraestructura de datos. El conector sondea constantemente la capa SaaS BlueXP para cualquier acción que necesite tomar. No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP. 
---
= Más información sobre conectores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _Connector_ es el software de NetApp que se ejecuta en la red del cloud o en las instalaciones. Ejecuta las acciones que BlueXP necesita realizar para gestionar su infraestructura de datos. El conector sondea constantemente la capa SaaS BlueXP para cualquier acción que necesite tomar. No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP.



== Lo que puede hacer sin un conector

No es necesario un conector para comenzar con BlueXP. Puede utilizar varias características y servicios dentro de BlueXP sin crear nunca un conector.

Puede utilizar las siguientes funciones y servicios de BlueXP sin un conector:

* Creación del entorno de trabajo de Amazon FSX para ONTAP de NetApp
+
Aunque no es necesario que un conector cree un entorno de trabajo, es necesario crear y gestionar volúmenes, replicar datos e integrar FSx para ONTAP con servicios como la clasificación de BlueXP y la copia y sincronización de BlueXP.

* Azure NetApp Files
+
Aunque no es necesario un conector para configurar y gestionar Azure NetApp Files, se necesita un conector para usar la clasificación de BlueXP para analizar datos de Azure NetApp Files.

* Cloud Volumes Service para Google Cloud
* Copiar y sincronizar
* Asesor digital
* Cartera digital
+
En casi todos los casos, puede agregar una licencia a la cartera digital sin un conector.

+
La única vez que se requiere un conector para agregar una licencia a la cartera digital es para licencias Cloud Volumes ONTAP _node-based_. En este caso, se requiere un conector porque los datos se toman de las licencias instaladas en los sistemas Cloud Volumes ONTAP.

* Detección directa de clústeres de ONTAP en las instalaciones
+
Aunque no es necesario un conector para la detección directa de un clúster ONTAP en las instalaciones, se necesita un conector si desea aprovechar las características adicionales de BlueXP.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Obtenga más información acerca de las opciones de detección y gestión para clústeres de ONTAP en las instalaciones"^]





== Cuando se necesita un conector

Al utilizar BlueXP en modo estándar, se necesita un conector para las siguientes funciones y servicios de BlueXP:

* Funciones de gestión de Amazon FSX para ONTAP
* Almacenamiento Amazon S3
* Almacenamiento de Azure Blob
* Backup y recuperación
* Clasificación
* Cloud Volumes ONTAP
* Sistemas E-Series
* Eficiencia económica ^1^
* Almacenamiento en caché en el edge
* Buckets de Google Cloud Storage
* Clústeres de Kubernetes
* Informes de migración
* Integración de clústeres de ONTAP en las instalaciones con servicios de datos de BlueXP
* Resistencia operativa ^1^
* Sistemas StorageGRID
* Organización en niveles
* Almacenamiento en caché de volúmenes


^1^ Mientras puede acceder a estos servicios sin un conector, se requiere un conector para iniciar acciones desde los servicios.



== Los conectores deben estar operativos en todo momento

Los conectores son una parte fundamental de la arquitectura de servicios de BlueXP. Es su responsabilidad asegurarse de que los conectores relevantes estén activos, operativos y accesibles en todo momento. Mientras que el servicio está diseñado para superar breves interrupciones de la disponibilidad del conector, debe tomar medidas inmediatas cuando sea necesario para solucionar fallos en la infraestructura.

Esta documentación se rige por el EULA. Si el producto no se utiliza de acuerdo con la documentación, la funcionalidad y el funcionamiento del producto, así como los derechos del usuario final, pueden verse afectados negativamente.



=== Impacto sobre Cloud Volumes ONTAP

Un conector es un componente clave en el estado y funcionamiento de Cloud Volumes ONTAP. Si el conector está apagado, los sistemas PAYGO de Cloud Volumes ONTAP y los sistemas BYOL basados en capacidad se apagan después de perder la comunicación con un conector durante más de 14 días. Esto sucede porque el conector actualiza las licencias del sistema cada día.

Si su sistema Cloud Volumes ONTAP tiene una licencia BYOL basada en nodos, el sistema seguirá ejecutándose transcurridos 14 días porque la licencia se instala en el sistema Cloud Volumes ONTAP.



== Ubicaciones admitidas

Se admite un conector en las siguientes ubicaciones:

* Amazon Web Services
* Microsoft Azure
+
Un conector en Azure debe ponerse en marcha en la misma región de Azure que los sistemas de Cloud Volumes ONTAP que gestione o en https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiones de Azure"^] Para los sistemas Cloud Volumes ONTAP. Este requisito garantiza que se utilice una conexión de enlace privado de Azure entre Cloud Volumes ONTAP y sus cuentas de almacenamiento asociadas. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Conozca cómo Cloud Volumes ONTAP utiliza un enlace privado de Azure"^]

* Google Cloud
+
Si desea utilizar los servicios de BlueXP con Google Cloud, debe utilizar un conector que se ejecute en Google Cloud.

* En sus instalaciones




== Modo restringido y modo privado

Para utilizar BlueXP en modo restringido o privado, se inicia con BlueXP instalando el conector y, a continuación, accediendo a la interfaz de usuario que se ejecuta localmente en el conector.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"].



== Cómo crear un conector

Un administrador de cuentas de BlueXP puede crear un conector directamente desde BlueXP, desde el mercado de su proveedor de la nube, o instalando manualmente el software en su propio host Linux. La forma de comenzar depende de si está utilizando BlueXP en modo estándar, modo restringido o modo privado.

* link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"]
* link:task-quick-start-standard-mode.html["Inicio rápido para BlueXP en modo estándar"]
* link:task-quick-start-restricted-mode.html["Inicio rápido para BlueXP en modo restringido"]
* link:task-quick-start-private-mode.html["Inicio rápido para BlueXP en modo privado"]




== Permisos

Se necesitan permisos específicos para crear el conector directamente desde BlueXP y se necesita otro conjunto de permisos para la propia instancia del conector. Si crea el conector en AWS o Azure directamente desde BlueXP, BlueXP crea el conector con los permisos que necesita.

Para aprender a configurar los permisos, consulte las siguientes páginas:

* Modo estándar
+
** link:task-set-up-permissions-aws.html["Configure los permisos de AWS"]
** link:task-set-up-permissions-azure.html["Configure los permisos de Azure"]
** link:task-set-up-permissions-google.html["Configure los permisos de Google Cloud"]
** link:task-set-up-permissions-on-prem.html["Configure permisos en el cloud para puestas en marcha en las instalaciones"]


* link:task-prepare-restricted-mode.html#prepare-cloud-permissions["Configure los permisos de cloud para el modo restringido"]
* link:task-prepare-private-mode.html#prepare-cloud-permissions["Configure permisos de cloud para el modo privado"]


Para ver los permisos exactos que necesita el conector, consulte las páginas siguientes:

* link:reference-permissions-aws.html["Conozca cómo el conector utiliza los permisos de AWS"]
* link:reference-permissions-azure.html["Conozca cómo el conector utiliza los permisos de Azure"]
* link:reference-permissions-gcp.html["Descubra cómo el conector utiliza los permisos de Google Cloud"]




== Actualizaciones de conectores

Normalmente actualizamos el software del conector cada mes para introducir nuevas funciones y para proporcionar mejoras de estabilidad. Aunque la mayoría de los servicios y características de la plataforma BlueXP se ofrecen a través de software basado en SaaS, algunas características y funciones dependen de la versión del conector. Que incluye gestión de Cloud Volumes ONTAP, gestión de clústeres ONTAP en las instalaciones, configuración y ayuda.

El conector actualiza automáticamente su software a la última versión, siempre que tenga acceso saliente a Internet para obtener la actualización de software. Si utiliza BlueXP en modo privado, deberá actualizar manualmente el conector.

link:task-managing-connectors.html["Aprenda a actualizar manualmente el software del conector"].



== Mantenimiento del sistema operativo y los equipos virtuales

El mantenimiento del sistema operativo en el host del conector es responsabilidad suya. Por ejemplo, debe aplicar actualizaciones de seguridad al sistema operativo en el host del conector siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo.

Tenga en cuenta que no es necesario detener ningún servicio en el host del conector cuando se ejecuta una actualización del SO.

Si necesita parar e iniciar el conector VM, debe hacerlo desde la consola de su proveedor de cloud o mediante los procedimientos estándar para la gestión en las instalaciones.

<<Los conectores deben estar operativos en todo momento,Tenga en cuenta que el conector debe estar operativo en todo momento>>.



== Múltiples entornos de trabajo

Un conector puede gestionar varios entornos de trabajo en BlueXP. El número máximo de entornos de trabajo que debe gestionar un único conector varía. Depende del tipo de entorno laboral, del número de volúmenes, de la cantidad de capacidad que se administra y del número de usuarios.

Si tiene una puesta en marcha a gran escala, trabaje con su representante de NetApp para dimensionar el entorno. Si experimenta algún problema a lo largo del camino, póngase en contacto con nosotros a través del chat en el producto.



== Múltiples conectores

En algunos casos, es posible que sólo necesite un conector, pero es posible que necesite dos o más conectores.

A continuación, se muestran algunos ejemplos:

* Tiene un entorno multicloud (por ejemplo, AWS y Azure) y prefiere tener un conector en AWS y otro en Azure. Cada una de ellas gestiona los sistemas Cloud Volumes ONTAP que se ejecutan en estos entornos.
* Un proveedor de servicios puede utilizar una cuenta de BlueXP para proporcionar servicios a sus clientes, mientras que usa otra cuenta para proporcionar recuperación ante desastres para una de sus unidades de negocio. Cada cuenta tendría conectores independientes.




=== Cuándo cambiar

Al crear el primer conector, BlueXP utiliza automáticamente ese conector para cada entorno de trabajo adicional que cree. Una vez creado un conector adicional, deberá cambiar entre ellos para ver los entornos de trabajo específicos de cada conector.

link:task-managing-connectors.html["Aprenda a cambiar entre conectores"].



=== Recuperación tras siniestros

Puede gestionar un entorno de trabajo con varios conectores al mismo tiempo para fines de recuperación ante desastres. Si se cae un conector, puede cambiar al otro conector para gestionar inmediatamente el entorno de trabajo.

Para configurar esta configuración:

. link:task-managing-connectors.html["Cambie a otro conector"].
. Detectar el entorno de trabajo existente.
+
** https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["Agregue sistemas Cloud Volumes ONTAP existentes a BlueXP"^]
** https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Detectar clústeres de ONTAP"^]


. Ajuste la https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage-management.html["Modo de gestión de la capacidad"^]
+
Sólo el conector principal debe ajustarse en *modo automático*. Si cambia a otro conector para fines de DR, puede cambiar el modo de gestión de capacidad según sea necesario.


