---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Un conector es el software de NetApp que se ejecuta en su red de cloud o en las instalaciones. Ejecuta las acciones que BlueXP necesita realizar para gestionar su infraestructura de datos. El conector sondea constantemente la capa SaaS BlueXP para cualquier acción que necesite tomar. No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP. 
---
= Obtenga más información sobre los conectores BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _Connector_ es el software de NetApp que se ejecuta en la red del cloud o en las instalaciones. Ejecuta las acciones que BlueXP necesita realizar para gestionar su infraestructura de datos. El conector sondea constantemente la capa de software como servicio (SaaS) de BlueXP  para cualquier acción que deba realizar. No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP.



== Lo que puede hacer sin un conector

No es necesario un conector para comenzar con BlueXP. Puede utilizar varias características y servicios dentro de BlueXP sin crear nunca un conector.

Puede utilizar las siguientes funciones y servicios de BlueXP sin un conector:

* Amazon FSX para ONTAP de NetApp
+
Algunas acciones requieren un conector o un enlace de fábrica de carga de trabajo BlueXP . https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Aprenda qué acciones requieren un conector o enlace"^]

* Catálogo de automatización
* Azure NetApp Files
+
Aunque no es necesario un conector para configurar y gestionar Azure NetApp Files, se necesita un conector para usar la clasificación de BlueXP para analizar datos de Azure NetApp Files.

* Cloud Volumes Service para Google Cloud
* Copiar y sincronizar
* Asesor digital
* Cartera digital (solo licencias, la supervisión de suscripciones requiere un conector)
+
En casi todos los casos, puede agregar una licencia a la cartera digital sin un conector.

+
La única vez que se requiere un conector para agregar una licencia a la cartera digital es para licencias Cloud Volumes ONTAP _node-based_. En este caso, se requiere un conector porque los datos se toman de las licencias instaladas en los sistemas Cloud Volumes ONTAP.

* Detección directa de clústeres de ONTAP en las instalaciones
+
Aunque no es necesario un conector para la detección directa de un clúster ONTAP en las instalaciones, se necesita un conector si desea aprovechar las características adicionales de BlueXP.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Obtenga más información sobre las opciones de descubrimiento y administración para clústeres ONTAP locales"^]

* Actualizaciones de software
* Sostenibilidad
* Fábrica de cargas de trabajo




== Cuando se necesita un conector

Al utilizar BlueXP en modo estándar, se necesita un conector para las siguientes funciones y servicios de BlueXP:

* Alertas
* Funciones de gestión de Amazon FSX para ONTAP
* Almacenamiento Amazon S3
* Almacenamiento de Azure Blob
* Backup y recuperación
* Clasificación
* Cloud Volumes ONTAP
* Recuperación tras siniestros
* Sistemas E-Series
* Eficiencia económica ^1^
* Buckets de Google Cloud Storage
* Integración de clústeres de ONTAP en las instalaciones con servicios de datos de BlueXP
* Resistencia operativa ^1^
* Protección contra ransomware
* Sistemas StorageGRID
* Organización en niveles
* Almacenamiento en caché de volúmenes


^1^ Mientras puede acceder a estos servicios sin un conector, se requiere un conector para iniciar acciones desde los servicios.

Se necesita un conector para utilizar BlueXP en modo restringido o en modo privado.



== Los conectores deben estar operativos en todo momento

Los conectores son una parte fundamental de la arquitectura de servicios de BlueXP. Es su responsabilidad asegurarse de que los conectores relevantes estén activos, operativos y accesibles en todo momento. Mientras que el servicio está diseñado para superar breves interrupciones de la disponibilidad del conector, debe tomar medidas inmediatas cuando sea necesario para solucionar fallos en la infraestructura.

Esta documentación se rige por el EULA. Si el producto no se utiliza de acuerdo con la documentación, la funcionalidad y el funcionamiento del producto, así como sus derechos bajo el EULA, podrían verse afectados negativamente.



== Ubicaciones admitidas

Se admite un conector en las siguientes ubicaciones:

* Amazon Web Services
* Microsoft Azure
+
Un conector en Azure debe ponerse en marcha en la misma región de Azure que los sistemas Cloud Volumes ONTAP que gestiona, o en el https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiones de Azure"^] para los sistemas Cloud Volumes ONTAP. Este requisito garantiza que se utilice una conexión de enlace privado de Azure entre Cloud Volumes ONTAP y sus cuentas de almacenamiento asociadas. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Conozca cómo Cloud Volumes ONTAP utiliza un enlace privado de Azure"^]

* Google Cloud
+
Si desea utilizar los servicios de BlueXP con Google Cloud, debe utilizar un conector que se ejecute en Google Cloud.

* En sus instalaciones




== Comunicación con proveedores de cloud

El conector utiliza TLS 1,3 para todas las comunicaciones con AWS, Azure y Google Cloud.



== Modo restringido y modo privado

Para utilizar BlueXP en modo restringido o privado, se inicia con BlueXP instalando el conector y, a continuación, accediendo a la interfaz de usuario que se ejecuta localmente en el conector.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"].



== Cómo instalar un conector

Puede instalar un conector directamente desde BlueXP, desde el marketplace de su proveedor de nube o instalando manualmente el software en su propio host Linux. La forma de comenzar depende de si está utilizando BlueXP en modo estándar, modo restringido o modo privado.

* link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"]
* link:task-quick-start-standard-mode.html["Empieza a usar BlueXP en el modo estándar"]
* link:task-quick-start-restricted-mode.html["Empieza a usar BlueXP en modo restringido"]
* link:task-quick-start-private-mode.html["Empieza a usar BlueXP en modo privado"]




== Permisos

Se necesitan permisos específicos para crear el conector directamente desde BlueXP y se necesita otro conjunto de permisos para la propia instancia del conector. Si crea el conector en AWS o Azure directamente desde BlueXP, BlueXP crea el conector con los permisos que necesita.

Cuando se utiliza BlueXP en el modo estándar, la forma de proporcionar permisos depende de cómo tengas previsto crear el Connector.

Para obtener más información sobre cómo configurar permisos, consulte lo siguiente:

* Modo estándar
+
** link:concept-install-options-aws.html["Opciones de instalación de conectores en AWS"]
** link:concept-install-options-azure.html["Opciones de instalación del conector en Azure"]
** link:concept-install-options-google.html["Opciones de instalación del conector en Google Cloud"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["Configurar permisos de nube para implementaciones locales"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configure los permisos para el modo restringido"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["Configurar permisos para el modo privado"]


Para ver los permisos exactos que el conector necesita para las operaciones diarias, consulte las siguientes páginas:

* link:reference-permissions-aws.html["Conozca cómo el conector utiliza los permisos de AWS"]
* link:reference-permissions-azure.html["Conozca cómo el conector utiliza los permisos de Azure"]
* link:reference-permissions-gcp.html["Descubra cómo el conector utiliza los permisos de Google Cloud"]


Es su responsabilidad actualizar las políticas de Connector a medida que se agregan nuevos permisos en las versiones posteriores. Si se requieren nuevos permisos, se mostrarán en las notas de la versión.



== Actualizaciones de conectores

Normalmente actualizamos el software del conector cada mes para introducir nuevas funciones y para proporcionar mejoras de estabilidad. Mientras que la mayoría de los servicios y características de la plataforma BlueXP  se ofrecen a través de software basado en SaaS, algunas características dependen de la versión del conector. Esto incluye la administración de Cloud Volumes ONTAP, la administración del clúster ONTAP local, la configuración y la ayuda.

Cuando usas BlueXP en modo estándar o en modo restringido, Connector actualiza automáticamente su software a la última versión, siempre y cuando tenga acceso a Internet saliente para obtener la actualización del software. Si utiliza BlueXP en modo privado, deberá actualizar manualmente el conector.

link:task-upgrade-connector.html["Aprenda a actualizar manualmente el software Connector cuando utilice el modo privado"].



== Mantenimiento del sistema operativo y los equipos virtuales

El mantenimiento del sistema operativo en el host del conector es responsabilidad de usted (cliente). Por ejemplo, usted (cliente) debe aplicar actualizaciones de seguridad al sistema operativo en el host de Connector siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo.

Tenga en cuenta que usted (cliente) no necesita detener ningún servicio en el host de Connector al aplicar actualizaciones de seguridad menores.

Si usted (cliente) necesita detener y luego iniciar la máquina virtual Connector, debe hacerlo desde la consola de su proveedor de cloud o mediante los procedimientos estándar para la gestión en las instalaciones.

<<Los conectores deben estar operativos en todo momento,Tenga en cuenta que el conector debe estar operativo en todo momento>>.



== Múltiples entornos de trabajo y conectores

Un conector puede gestionar varios entornos de trabajo en BlueXP. El número máximo de entornos de trabajo que debe gestionar un único conector varía. Depende del tipo de entorno laboral, del número de volúmenes, de la cantidad de capacidad que se administra y del número de usuarios.

Si tiene una puesta en marcha a gran escala, trabaje con su representante de NetApp para dimensionar el entorno. Si experimenta algún problema a lo largo del camino, póngase en contacto con nosotros a través del chat en el producto.

En algunos casos, es posible que sólo necesite un conector, pero es posible que necesite dos o más conectores.

A continuación, se muestran algunos ejemplos:

* Tienes un entorno multicloud (por ejemplo, AWS y Azure) y prefieres tener un Conector en AWS y otro en Azure. Cada una de ellas gestiona los sistemas Cloud Volumes ONTAP que se ejecutan en estos entornos.
* Un proveedor de servicios puede utilizar una organización de BlueXP  para proporcionar servicios a sus clientes, mientras utiliza otra organización para prestar recuperación ante desastres a una de sus unidades de negocio. Cada organización tendría conectores separados.

