---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP proporciona a su organización un plano de control único que le ayuda a crear, proteger y dirigir los datos tanto en sus instalaciones como en sus entornos de cloud. La plataforma SaaS BlueXP incluye servicios de almacenamiento y datos que proporcionan gestión del almacenamiento, movilidad de datos, protección de datos, análisis y control de los datos. Las capacidades de gestión se proporcionan a través de una consola basada en web y API. 
---
= Más información sobre BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP proporciona a su organización un plano de control único que le ayuda a crear, proteger y dirigir los datos tanto en sus instalaciones como en sus entornos de cloud. La plataforma SaaS BlueXP incluye servicios de almacenamiento y datos que proporcionan gestión del almacenamiento, movilidad de datos, protección de datos, análisis y control de los datos. Las capacidades de gestión se proporcionan a través de una consola basada en web y API.



== Funciones

La plataforma BlueXP proporciona cuatro pilares principales de la gestión de datos: Almacenamiento, movilidad, protección, análisis y control.

Reducida:: Descubra, ponga en marcha y gestione el almacenamiento, ya sea en AWS, Azure, Google Cloud o en las instalaciones.
+
--
* Configuración y uso https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] para lograr una gestión de datos eficiente con varios protocolos en todos los clouds.
* Configure y utilice los servicios cloud de almacenamiento de archivos:
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX para ONTAP"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service para Google Cloud"^]


* Detectar y gestionar https://bluexp.netapp.com/netapp-on-premises["almacenamiento en las instalaciones"^]:
+
** Sistemas E-Series
** Clústeres ONTAP
** Sistemas StorageGRID


* Orquestar y proteger https://bluexp.netapp.com/solutions/kubernetes["Datos persistentes de Kubernetes"^]


--
Movilidad:: Mueva los datos donde los necesite sincronizando, copiando, organizando en niveles y almacenando los datos en caché.
+
--
* https://bluexp.netapp.com/cloud-sync-service["Copiar y sincronizar"^]
* https://bluexp.netapp.com/global-file-cache["Almacenamiento en caché en el edge"^]
* https://bluexp.netapp.com/cloud-tiering["Organización en niveles"^]


--
Protección:: Use mecanismos de protección automatizados para proteger los datos contra la pérdida de datos, interrupciones del servicio no planificadas, ransomware y otras amenazas cibernéticas.
+
--
* https://bluexp.netapp.com/cloud-backup["Backup y recuperación"^]
* https://bluexp.netapp.com/replication["Replicación"^]


--
Análisis y control:: Use herramientas para supervisar, asignar y optimizar su almacenamiento de datos y su infraestructura.
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["Clasificación"^]
* https://bluexp.netapp.com/digital-advisor["Asesor digital"^]
* https://bluexp.netapp.com/digital-advisor["Eficiencia económica"^]
* https://bluexp.netapp.com/digital-advisor["Resiliencia operativa"^]
* https://bluexp.netapp.com/ransomware-protection["Protección contra ransomware"^]


--


https://bluexp.netapp.com/["Obtenga más información sobre cómo puede utilizar BlueXP para ayudar a su organización"^]



== Proveedores de cloud compatibles

BlueXP le permite gestionar el almacenamiento en cloud y utilizar servicios cloud en Amazon Web Services, Microsoft Azure y Google Cloud.



== Coste

El precio de BlueXP depende de los servicios que usted planea utilizar. https://bluexp.netapp.com/pricing["Más información sobre los precios de BlueXP"^]



== Cómo funciona BlueXP

BlueXP incluye una consola basada en web que se proporciona a través de la capa de SaaS, cuentas que proporcionan multi-tenancy y conectores que gestionan los entornos de trabajo y habilitan los servicios en la nube de BlueXP.



=== Software como servicio

BlueXP es accesible a través de un https://console.bluexp.netapp.com["consola basada en web"^] Y API. Esta experiencia SaaS le permite acceder automáticamente a las últimas funciones a medida que se publican y cambiar fácilmente entre sus cuentas y conectores de BlueXP.



=== Cuenta BlueXP

Cuando inicia sesión en BlueXP por primera vez, se le pide que cree una cuenta _BlueXP_. Esta cuenta proporciona multi-tenancy y le permite organizar usuarios y recursos en espacios de trabajo aislados.

link:concept-netapp-accounts.html["Más información acerca de las cuentas"].



=== Conectores

No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP. Un conector permite la gestión de recursos y procesos en sus entornos locales y de cloud. Es necesario gestionar entornos de trabajo (por ejemplo, Cloud Volumes ONTAP y clústeres de ONTAP en las instalaciones) y usar muchos servicios de datos de BlueXP.

link:concept-connectors.html["Más información sobre conectores"].



=== Modo restringido y modo privado

BlueXP también es compatible en entornos que tienen restricciones de seguridad y conectividad. Puede utilizar _restricted mode_ o _private mode_ para limitar la conectividad saliente a la capa SaaS BlueXP.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"].



== Certificación SOC 2 de tipo 2

Una firma de contabilidad pública independiente certificada y un auditor de servicios examinó BlueXP y afirmó que logró los informes SOC 2 de tipo 2 basados en los criterios aplicables de los servicios de confianza.

https://www.netapp.com/company/trust-center/compliance/soc-2/["Consulte los informes de SOC 2 de NetApp"^]
