---
sidebar: sidebar 
permalink: concept-install-options-azure.html 
keywords: install connector azure, azure install connector, connector azure, azure connector, installation options, azure marketplace, manual install 
summary: Hay varias formas diferentes de crear un conector en Azure. Directamente desde BlueXP es la forma más común. 
---
= Opciones de instalación del conector en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varias formas diferentes de crear un conector en Azure. Directamente desde BlueXP es la forma más común.

Están disponibles las siguientes opciones de instalación:

* Crear el conector directamente desde BlueXP (esta es la opción estándar)
+
Esta acción lanza una VM que ejecuta Linux y el software Connector en una vnet de su elección.

* Cree un conector desde Azure Marketplace
+
Esta acción también inicia una máquina virtual que ejecuta Linux y el software Connector.

* Descargue e instale manualmente el software en su propio host Linux


La opción de instalación que elija afectará a la forma en que se prepara para la instalación. Esto incluye cómo proporciona BlueXP los permisos necesarios para autenticar y gestionar recursos en Azure.

link:task-install-connector-azure.html["Aprenda a instalar Connector en Azure"].
