---
sidebar: sidebar 
permalink: concept-install-options-google.html 
keywords: install connector google cloud, google cloud install connector, connector google cloud, google cloud connector, install connector gcp, gcp install connector, connector gcp, gcp connector, installation options, manual install 
summary: Hay varias formas diferentes de crear un conector en Google Cloud. Directamente desde BlueXP es la forma más común. 
---
= Opciones de instalación del conector en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varias formas diferentes de crear un conector en Google Cloud. Directamente desde BlueXP es la forma más común.

Están disponibles las siguientes opciones de instalación:

* Crear el conector directamente desde BlueXP (esta es la opción estándar)
+
Esta acción inicia una instancia de máquina virtual que ejecuta Linux y el software Connector en un VPC de su elección.

* Cree el conector con gcloud
+
Esta acción también inicia una instancia de máquina virtual que ejecuta Linux y el software Connector.

* Descargue e instale manualmente el software en su propio host Linux


La opción de instalación que elija afectará a la forma en que se prepara para la instalación. Esto incluye cómo proporciona BlueXP los permisos necesarios para autenticar y administrar recursos en Google Cloud.

link:task-install-connector-google.html["Aprenda a instalar el conector en Google Cloud"].
