---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP proporciona a su organización un plano de control único que le ayuda a crear, proteger y dirigir los datos tanto en sus instalaciones como en sus entornos de cloud. La plataforma SaaS de BlueXP incluye servicios que proporcionan gestión del almacenamiento, movilidad de datos, protección de datos, y análisis y control de los datos. Las capacidades de gestión se proporcionan a través de una consola basada en web y API. 
---
= Más información sobre BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP proporciona a su organización un plano de control único que le ayuda a crear, proteger y dirigir los datos tanto en sus instalaciones como en sus entornos de cloud. La plataforma SaaS de BlueXP incluye servicios que proporcionan gestión del almacenamiento, movilidad de datos, protección de datos, y análisis y control de los datos. Las capacidades de gestión se proporcionan a través de una consola basada en web y API.



== Funciones

La plataforma BlueXP proporciona cuatro pilares principales de la gestión de datos: Almacenamiento, movilidad, protección, análisis y control.

Reducida:: Detecta, pon en marcha y gestiona el almacenamiento, ya sea en AWS, Azure, Google Cloud o en las instalaciones.
+
--
* Configure y utilice los servicios cloud de almacenamiento de archivos:
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["Amazon FSX para ONTAP de NetApp"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service para Google Cloud"^]


* Configuración y uso https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] para lograr una gestión de datos eficiente con varios protocolos en todos los clouds.
* Detectar y gestionar https://bluexp.netapp.com/netapp-on-premises["almacenamiento en las instalaciones"^]:
+
** Sistemas E-Series
** Clústeres ONTAP
** Sistemas StorageGRID




--
Movilidad:: Mueva los datos donde los necesite mediante la sincronización, la copia y la organización en niveles de los datos.
+
--
* https://bluexp.netapp.com/cloud-sync-service["Copiar y sincronizar"^]
* https://bluexp.netapp.com/cloud-tiering["Organización en niveles"^]


--
Protección:: Use mecanismos de protección automatizados para proteger los datos contra la pérdida de datos, interrupciones del servicio no planificadas, ransomware y otras amenazas cibernéticas.
+
--
* https://bluexp.netapp.com/cloud-backup["Backup y recuperación"^]
* https://bluexp.netapp.com/disaster-recovery["Recuperación tras siniestros"^]
* https://bluexp.netapp.com/replication["Replicación"^]
* https://bluexp.netapp.com/ransomware-protection["Protección contra ransomware"^]


--
Análisis y control:: Use herramientas para supervisar, asignar y optimizar su almacenamiento de datos y su infraestructura. Obtenga información procesable para optimizar el estado, la resiliencia y la economía del almacenamiento.
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["Clasificación"^]
* https://bluexp.netapp.com/digital-advisor["Asesor digital"^]
* https://bluexp.netapp.com/digital-advisor["Eficiencia económica"^]
* https://bluexp.netapp.com/digital-advisor["Resiliencia operativa"^]


--


https://bluexp.netapp.com/["Más información sobre cómo puede utilizar BlueXP  para gestionar datos en su entorno multicloud híbrido"^]



== Proveedores de cloud compatibles

BlueXP le permite gestionar el almacenamiento en cloud y utilizar servicios cloud en Amazon Web Services, Microsoft Azure y Google Cloud.



== Coste

El precio de BlueXP depende de los servicios que usted planea utilizar. https://bluexp.netapp.com/pricing["Más información sobre los precios de BlueXP"^]



== Cómo funciona BlueXP

BlueXP  incluye una consola basada en web que se proporciona a través de la capa SaaS, un sistema de administración de acceso y recursos, y conectores que administran los entornos de trabajo y habilitan los servicios en la nube de BlueXP .



=== Software como servicio

Se puede acceder a BlueXP  a través de las API de la A https://console.bluexp.netapp.com["consola basada en web"^] y. Esta experiencia SaaS le permite acceder automáticamente a las últimas funciones a medida que se lanzan y cambiar fácilmente entre sus organizaciones, proyectos y conectores de BlueXP .



=== Gestión de identidades y accesos (IAM) de BlueXP 

La gestión de acceso e identidad (IAM) de BlueXP  es un modelo de gestión de recursos y accesos que proporciona gestión granular de recursos y permisos:

* Un nivel superior _ORGANIZATION_ le permite administrar el acceso a través de sus diversos _PROYECTOS_
* _Folders_ le permite agrupar proyectos relacionados
* La gestión de recursos permite asociar un recurso a una o más carpetas o proyectos
* La gestión de acceso permite asignar un rol a miembros de distintos niveles de la jerarquía de la organización


BlueXP  IAM es compatible cuando se utiliza BlueXP  en modo estándar. Si utiliza BlueXP  en modo restringido o privado, utilizará una _account_ de BlueXP  para gestionar espacios de trabajo, usuarios y recursos.

* link:concept-identity-and-access-management.html["Obtenga más información sobre BlueXP  IAM"]
* link:concept-netapp-accounts.html["Obtenga más información sobre las cuentas de BlueXP"]




=== Conectores

No necesitas un conector para empezar con BlueXP, pero tendrás que crear un conector para desbloquear todas las funciones y servicios de BlueXP. Un conector permite la gestión de recursos y procesos en sus entornos locales y de cloud. Es necesario gestionar entornos de trabajo (por ejemplo, Cloud Volumes ONTAP) y utilizar muchos servicios de BlueXP .

link:concept-connectors.html["Más información sobre conectores"].



=== Modos de implementación

BlueXP  es compatible con entornos con restricciones de seguridad y conectividad. Puede utilizar _restricted mode_ o _private mode_ para limitar la conectividad saliente a la capa SaaS BlueXP.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"].



== Certificación SOC 2 de tipo 2

Una firma de contabilidad pública independiente certificada y un auditor de servicios examinó BlueXP y afirmó que logró los informes SOC 2 de tipo 2 basados en los criterios aplicables de los servicios de confianza.

https://www.netapp.com/company/trust-center/compliance/soc-2/["Consulte los informes de SOC 2 de NetApp"^]
