---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de configuración y administración
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones
      url: "/reference-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Aprenda lo básico
      entries:
      - title: Introducción a BlueXP
        url: "/concept-overview.html"
      - title: Cuentas
        url: "/concept-netapp-accounts.html"
      - title: Conectores
        url: "/concept-connectors.html"
      - title: Modos de implementación
        url: "/concept-modes.html"
    - title: Comience con el modo estándar
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-standard-mode.html"
      - title: Prepare las redes para usar la consola de BlueXP
        url: "/reference-networking-saas-console.html"
      - title: Regístrese en BlueXP
        url: "/task-sign-up-saas.html"
      - title: Cree un conector
        entries:
        - title: AWS
          entries:
          - title: Las opciones de instalación
            url: "/concept-install-options-aws.html"
          - title: Crea desde BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Crear desde el mercado
            url: "/task-install-connector-aws-marketplace.html"
          - title: Instale manualmente
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Las opciones de instalación
            url: "/concept-install-options-azure.html"
          - title: Crea desde BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Crear desde el mercado
            url: "/task-install-connector-azure-marketplace.html"
          - title: Instale manualmente
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Las opciones de instalación
            url: "/concept-install-options-google.html"
          - title: Crea desde BlueXP o mediante gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Instale manualmente
            url: "/task-install-connector-google-manual.html"
        - title: En el entorno local
          url: "/task-install-connector-on-prem.html"
      - title: Suscríbase a BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next.html"
    - title: Comience con el modo restringido
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepárese para la puesta en marcha
        url: "/task-prepare-restricted-mode.html"
      - title: Despliegue el conector
        url: "/task-install-restricted-mode.html"
      - title: Suscríbase a BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next-restricted-mode.html"
    - title: Comience con el modo privado
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-private-mode.html"
      - title: Prepárese para la puesta en marcha
        url: "/task-prepare-private-mode.html"
      - title: Despliegue el conector
        url: "/task-install-private-mode.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next-private-mode.html"
    - title: Inicie sesión en BlueXP
      url: "/task-logging-in.html"
  - title: Administrar BlueXP
    entries:
    - title: federación de identidades
      url: "/concept-federation.html"
    - title: Cuentas BlueXP
      entries:
      - title: Gestione su cuenta
        url: "/task-managing-netapp-accounts.html"
      - title: Supervisar las operaciones en su cuenta
        url: "/task-monitor-cm-operations.html"
      - title: Cree otra cuenta
        url: "/task-create-account.html"
      - title: Roles de usuario
        url: "/reference-user-roles.html"
    - title: Conectores
      entries:
      - title: Busque el ID del sistema de un conector
        url: "/task-finding-system-id.html"
      - title: Administrar conectores existentes
        url: "/task-managing-connectors.html"
      - title: Instale un certificado HTTPS
        url: "/task-installing-https-cert.html"
      - title: Configure los ajustes de proxy
        url: "/task-configuring-proxy.html"
      - title: Configuración predeterminada
        url: "/reference-connector-default-config.html"
    - title: Credenciales
      entries:
      - title: Gestione las credenciales de AWS
        entries:
        - title: Descripción general
          url: "/concept-accounts-aws.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-aws-accounts.html"
      - title: Gestione las credenciales de Azure
        entries:
        - title: Descripción general
          url: "/concept-accounts-azure.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-azure-accounts.html"
      - title: Gestione las credenciales de Google Cloud
        entries:
        - title: Descripción general
          url: "/concept-accounts-gcp.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-gcp-accounts.html"
      - title: Administrar las credenciales de NSS asociadas con una cuenta de BlueXP
        url: "/task-adding-nss-accounts.html"
      - title: Administre las credenciales asociadas con su inicio de sesión de BlueXP
        url: "/task-manage-user-credentials.html"
    - title: Almacenamiento en cloud detectado
      entries:
      - title: Gestione sus bloques de Amazon S3
        url: "/task-viewing-amazon-s3.html"
      - title: Gestione sus cuentas de Azure Blob
        url: "/task-viewing-azure-blob.html"
      - title: Gestiona tus buckets de Google Cloud Storage
        url: "/task-viewing-gcp-storage.html"
  - title: Referencia
    entries:
    - title: Permisos
      entries:
      - title: Resumen de permisos
        url: "/reference-permissions.html"
      - title: Permisos de AWS para Connector
        url: "/reference-permissions-aws.html"
      - title: Permisos de Azure para Connector
        url: "/reference-permissions-azure.html"
      - title: Permisos de Google Cloud para Connector
        url: "/reference-permissions-gcp.html"
    - title: Puertos
      entries:
      - title: Reglas del grupo de seguridad en AWS
        url: "/reference-ports-aws.html"
      - title: Reglas de grupos de seguridad en Azure
        url: "/reference-ports-azure.html"
      - title: Reglas de firewall en Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Puertos para el conector en las instalaciones
        url: "/reference-ports-on-prem.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Más información sobre BlueXP
      url: concept-overview.html
    - title: Obtenga información sobre los modos de implementación
      url: concept-modes.html
    - title: Comience con el modo estándar
      url: "/task-quick-start-standard-mode.html"
    - title: Comience con el modo restringido
      url: "/task-quick-start-restricted-mode.html"
    - title: Comience con el modo privado
      url: "/task-quick-start-private-mode.html"
  - title: Cuentas BlueXP
    links:
    - title: Obtenga más información sobre las cuentas de BlueXP
      url: concept-netapp-accounts.html
    - title: Administre su cuenta de BlueXP
      url: task-managing-netapp-accounts.html
    - title: Supervisar las operaciones en su cuenta
      url: task-monitor-cm-operations.html
  - title: Conectores
    links:
    - title: Más información sobre conectores
      url: concept-connectors.html
    - title: Crear un conector en AWS (modo estándar)
      url: task-install-connector-aws-bluexp.html
    - title: Crear un conector en Azure (modo estándar)
      url: task-install-connector-azure-bluexp.html
    - title: Crear un conector en Google Cloud (modo estándar)
      url: task-install-connector-google-bluexp-gcloud.html
    - title: Crear un conector en las instalaciones (modo estándar)
      url: task-install-connector-on-prem.html
    - title: Gestionar conectores
      url: task-managing-connectors.html
  - title: Permisos
    links:
    - title: Resumen de permisos
      url: reference-permissions.html
    - title: Permisos de AWS para Connector
      url: reference-permissions-aws.html
    - title: Permisos de Azure para Connector
      url: reference-permissions-azure.html
    - title: Permisos de Google Cloud para Connector
      url: reference-permissions-gcp.html
  - title: Credenciales
    links:
    - title: Gestione las credenciales de AWS
      url: task-adding-aws-accounts.html
    - title: Gestione las credenciales de Azure
      url: task-adding-azure-accounts.html
    - title: Gestione las credenciales de Google Cloud
      url: task-adding-gcp-accounts.html
    - title: Gestione las credenciales de NSS para su cuenta
      url: task-adding-nss-accounts.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
