---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Configuración y administración de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/reference-limitations.html"
    - title: Cambios en los sistemas operativos Linux admitidos
      url: "/reference-connector-operating-system-changes.html"
  - title: Manos a la obra
    entries:
    - title: Aprenda lo básico
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Conectores
        url: "/concept-connectors.html"
      - title: Modos de implementación
        url: "/concept-modes.html"
    - title: Comience con el modo estándar
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-standard-mode.html"
      - title: Prepare las redes para la consola de BlueXP 
        url: "/reference-networking-saas-console.html"
      - title: Regístrese en BlueXP
        url: "/task-sign-up-saas.html"
      - title: Cree un conector
        entries:
        - title: AWS
          entries:
          - title: Opciones de instalación del conector
            url: "/concept-install-options-aws.html"
          - title: Cree un conector desde BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Cree un conector desde el mercado
            url: "/task-install-connector-aws-marketplace.html"
          - title: Instale manualmente el conector
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Opciones de instalación del conector
            url: "/concept-install-options-azure.html"
          - title: Cree un conector desde BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Cree un conector desde el mercado
            url: "/task-install-connector-azure-marketplace.html"
          - title: Instale manualmente el conector
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opciones de instalación del conector
            url: "/concept-install-options-google.html"
          - title: Crea un conector desde BlueXP o gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Instale manualmente el conector
            url: "/task-install-connector-google-manual.html"
        - title: Localmente
          url: "/task-install-connector-on-prem.html"
      - title: Suscríbase a los servicios inteligentes de NetApp
        url: "/task-subscribe-standard-mode.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next.html"
    - title: Comience con el modo restringido
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepárese para la puesta en marcha
        url: "/task-prepare-restricted-mode.html"
      - title: Despliegue el conector
        url: "/task-install-restricted-mode.html"
      - title: Suscríbase a los servicios inteligentes de NetApp
        url: "/task-subscribe-restricted-mode.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next-restricted-mode.html"
    - title: Comience con el modo privado
      entries:
      - title: Flujo de trabajo inicial
        url: "/task-quick-start-private-mode.html"
      - title: Prepárese para la puesta en marcha
        url: "/task-prepare-private-mode.html"
      - title: Despliegue el conector
        url: "/task-install-private-mode.html"
      - title: Cuentas BlueXP
        entries:
        - title: Más información acerca de las cuentas
          url: "/concept-netapp-accounts.html"
        - title: Administre su cuenta de BlueXP
          url: "/task-managing-netapp-accounts.html"
      - title: Lo que puede hacer a continuación
        url: "/reference-whats-next-private-mode.html"
  - title: Utilice BlueXP
    entries:
    - title: Inicie sesión en BlueXP
      url: "/task-logging-in.html"
    - title: Administra tu configuración de usuario de BlueXP
      url: "/task-user-settings.html"
  - title: Administrar BlueXP
    entries:
    - title: Gestión de identidades y accesos
      entries:
      - title: Obtenga más información sobre BlueXP  IAM
        url: "/concept-identity-and-access-management.html"
      - title: Comience a usar BlueXP  IAM
        url: "/task-iam-get-started.html"
      - title: Organiza tus recursos con carpetas y proyectos
        url: "/task-iam-manage-folders-projects.html"
      - title: Administrar miembros y cuentas de servicio
        url: "/task-iam-manage-members-permissions.html"
      - title: Utilice roles para controlar el acceso de los miembros a los recursos
        url: "/task-iam-manage-roles.html"
      - title: Gestione la jerarquía de recursos
        url: "/task-iam-manage-resources.html"
      - title: Asociar un conector a otras carpetas y proyectos
        url: "/task-iam-associate-connectors.html"
      - title: Cambiar entre organizaciones, proyectos y conectores
        url: "/task-iam-switch-organizations-projects.html"
      - title: ID de organización y proyecto
        url: "/task-iam-rename-organization.html"
      - title: Supervisar o auditar la actividad de IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Roles de acceso de BlueXP
        entries:
        - title: Obtenga más información sobre los roles de acceso de BlueXP 
          url: "/reference-iam-predefined-roles.html"
        - title: Funciones de la plataforma
          url: "/reference-iam-platform-roles.html"
        - title: Funciones de la aplicación
          entries:
          - title: Roles de Keystone
            url: "/reference-iam-keystone-roles.html"
          - title: Roles de almacenamiento
            url: "/reference-iam-storage-roles.html"
        - title: Roles de servicios de datos
          entries:
          - title: Funciones de protección contra ransomware
            url: "/reference-iam-ransomware-roles.html"
    - title: Cuentas de BlueXP  (solo modo privado)
      entries:
      - title: Más información acerca de las cuentas
        url: "/concept-netapp-accounts.html"
      - title: Administre su cuenta de BlueXP
        url: "/task-managing-netapp-accounts.html"
    - title: federación de identidades
      url: "/concept-federation.html"
    - title: Conectores
      entries:
      - title: Mantener la máquina virtual y el SO
        url: "/task-maintain-connectors.html"
      - title: Instale un certificado firmado por CA para acceder a la consola web
        url: "/task-installing-https-cert.html"
      - title: Configure un conector para que utilice un servidor proxy
        url: "/task-configuring-proxy.html"
      - title: Requiere el uso de IMDSv2 en instancias EC2
        url: "/task-require-imdsv2.html"
      - title: Gestionar actualizaciones de conectores
        url: "/task-upgrade-connector.html"
      - title: Trabaje con varios conectores
        url: "/task-manage-multiple-connectors.html"
      - title: Localice y solucione los problemas del conector
        url: "/task-troubleshoot-connector.html"
      - title: Desinstale y retire el conector
        url: "/task-uninstall-connector.html"
      - title: Configuración predeterminada
        url: "/reference-connector-default-config.html"
      - title: Aplique los permisos de ONTAP en BlueXP 
        url: "/task-ontap-access-connector.html"
    - title: Credenciales y suscripciones
      entries:
      - title: AWS
        entries:
        - title: Obtenga más información sobre las credenciales y los permisos
          url: "/concept-accounts-aws.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: Obtenga más información sobre las credenciales y los permisos
          url: "/concept-accounts-azure.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Aprende sobre proyectos y permisos
          url: "/concept-accounts-gcp.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-gcp-accounts.html"
      - title: Gestione las credenciales de NSS asociadas a una organización o cuenta
          de BlueXP 
        url: "/task-adding-nss-accounts.html"
      - title: Administre las credenciales asociadas con su inicio de sesión de BlueXP
        url: "/task-manage-user-credentials.html"
    - title: Supervise las operaciones de BlueXP 
      url: "/task-monitor-cm-operations.html"
  - title: Referencia
    entries:
    - title: Permisos
      entries:
      - title: Resumen de permisos
        url: "/reference-permissions.html"
      - title: Permisos de AWS para Connector
        url: "/reference-permissions-aws.html"
      - title: Permisos de Azure para Connector
        url: "/reference-permissions-azure.html"
      - title: Permisos de Google Cloud para Connector
        url: "/reference-permissions-gcp.html"
    - title: Puertos
      entries:
      - title: Reglas de grupo de seguridad de conector en AWS
        url: "/reference-ports-aws.html"
      - title: Reglas de grupo de seguridad de conector en Azure
        url: "/reference-ports-azure.html"
      - title: Reglas de firewall de conector en Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Puertos para el conector local
        url: "/reference-ports-on-prem.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
