---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Estas limitaciones son específicas para la configuración y administración de BlueXP: El conector, la plataforma SaaS, y más.



== Limitaciones del conector



=== Se requiere IMDSv1 en instancias de EC2

Antes de instalar manualmente el software Connector en una instancia de EC2 en AWS cuando se utiliza el modo estándar o el modo restringido, debe asegurarse de que la instancia de EC2 utiliza la instancia de Metadata Service versión 1 (IMDSv1). El conector no es compatible con IMDSv2.

Puesto que IMDSv2 es ahora la versión predeterminada en una nueva instancia de EC2, es necesario modificar las opciones de metadatos de la instancia para restaurar el uso de IMDSv1.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-restore-IMDSv1["Documentación de AWS: Restaurar el uso de IMDSv1"^]



=== No se debe cambiar la configuración de instancia de EC2 por defecto

Al implementar el conector en AWS desde BlueXP o desde AWS Marketplace, se configuran de forma predeterminada los siguientes ajustes de instancia de EC2:

* IMDSv2 está configurado como opcional
* HttpTokens está configurado como opcional


Estos ajustes no se deben cambiar a Necesario. El cambio de estos ajustes a necesarios afecta a la disponibilidad de conectores y Cloud Volumes ONTAP.



=== Posible conflicto con las direcciones IP en el rango 172

BlueXP despliega el conector con dos interfaces que tienen direcciones IP en las gamas 172.17.0.0/16 y 172.18.0.0/16.

Si la red tiene una subred configurada con cualquiera de estos rangos, puede que experimente errores de conectividad de BlueXP. Por ejemplo, la detección de clústeres de ONTAP en las instalaciones en BlueXP podría fallar.

Consulte el artículo de Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["BlueXP Connector IP entra en conflicto con la red existente"] Para obtener instrucciones sobre cómo cambiar la dirección IP de las interfaces del conector.



=== El descifrado SSL no es compatible

BlueXP no admite configuraciones de firewall que tengan activado el descifrado SSL. Si está activado el descifrado SSL, aparecerán mensajes de error en BlueXP y la instancia del conector aparecerá como inactiva.

Para mejorar la seguridad, tiene la opción de link:task-installing-https-cert.html["Instalar un certificado HTTPS firmado por una entidad de certificación (CA)"].



=== Página en blanco al cargar la interfaz de usuario local

Si carga la consola basada en web que se ejecuta en un conector, es posible que la interfaz no se muestre a veces y sólo se obtiene una página en blanco.

Este problema está relacionado con un problema del almacenamiento en caché. La solución alternativa es usar una sesión de navegador web privada o de incógnito.



=== No se admiten los hosts Linux compartidos

El conector no es compatible con una máquina virtual compartida con otras aplicaciones. La máquina virtual debe estar dedicada al software del conector.



=== agentes y extensiones de terceros

No se admiten agentes de terceros ni extensiones de VM en el conector VM.
