---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Asignar roles de plataforma a los usuarios para otorgar permisos para administrar BlueXP, asignar roles, agregar usuarios, crear conectores y administrar federaciones. 
---
= Funciones de acceso a la plataforma BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Asignar roles de plataforma a los usuarios para otorgar permisos para administrar BlueXP, asignar roles, agregar usuarios, crear conectores y administrar federaciones.

.Ejemplo de roles de organización en BlueXP  para una organización multinacional grande
XYZ Corporation organiza el acceso al almacenamiento de datos por región (América del Norte, Europa y Asia-Pacífico), lo que otorga control a cada región y garantiza una supervisión centralizada.

El *administrador de la organización* en BlueXP de XYZ Corporation crea una organización inicial y carpetas separadas para cada región. La carpeta de cada región contiene proyectos (con recursos asociados) relacionados con esa región. El *Administrador de la organización* asigna a un usuario de BlueXP  en cada región respectiva la función *Carpeta o administrador del proyecto*.

Los administradores regionales con el rol de *Administrador de carpetas o proyectos* administran sus regiones (carpetas) añadiendo nuevos recursos y usuarios. Estos administradores regionales también pueden añadir, eliminar o renombrar las carpetas y los proyectos que gestionan. El *Administrador de la organización* hereda los permisos de cualquier recurso nuevo, lo que permite mantener la visibilidad del uso del almacenamiento en toda la organización.

Dentro de la misma organización, a un usuario se le asigna el rol de *Administrador de federación* para gestionar la federación de la organización con su IdP corporativo. Este usuario puede agregar o eliminar organizaciones federadas, pero no puede administrar usuarios ni recursos dentro de la organización. La organización asigna a un usuario el rol de *Visor de federación* para comprobar el estado de la federación y ver las organizaciones federadas sin realizar cambios.

Las siguientes tablas indican las acciones que cada rol de la plataforma BlueXP puede realizar.



== Roles de administración de la organización

[cols="2,1,1"]
|===
| Tarea | Administrador de la organización | Administrador de carpetas o proyectos 


| Crear conectores | Sí | No 


| Crear, modificar o suprimir entornos de trabajo (añadir o detectar nuevos recursos mediante el lienzo de BlueXP ) | Sí | Sí 


| Cree carpetas y proyectos, incluida la eliminación | Sí | No 


| Cambie el nombre de las carpetas y proyectos existentes | Sí | Sí 


| Asigne roles y añada usuarios | Sí | Sí 


| Asociar recursos a carpetas y proyectos | Sí | Sí 


| Asociar conectores a carpetas y proyectos | Sí | No 


| Eliminar conectores de carpetas y proyectos | Sí | No 


| Administrar conectores (editar certificados, configuración, etc.) | Sí | No 


| Gestione credenciales desde Configuración > Credenciales | Sí | Sí 


| Crear, administrar y visualizar federaciones | Sí | No 


| Regístrese para recibir soporte y enviar casos | Sí | Sí 


| Utilizar servicios de datos | Sí | Sí 


| Ver la línea de tiempo y las notificaciones de BlueXP | Sí | Sí 
|===


== Roles de la federación

[cols="2,1,1"]
|===
| Tarea | Administración de la federación | Visor de la Federación 


| Crear una federación | Sí | No 


| Verificar un dominio | Sí | No 


| Agregar un dominio a una federación | Sí | No 


| Deshabilitar y eliminar federaciones | Sí | No 


| Federaciones de pruebas | Sí | No 


| Ver federaciones y sus detalles | Sí | Sí 
|===