---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Al usar la consola basada en web de BlueXP que se proporciona a través de la capa SaaS, se pone en contacto con varios extremos cuando completa unas pocas tareas administrativas. Los equipos que accedan a la consola de BlueXP deben tener conexiones a estos extremos. 
---
= Prepare las redes para la consola de BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al iniciar sesión y usar la consola web, BlueXP se conecta a varios endpoints para completar las acciones que usted inicia. Los equipos que acceden a la consola deben tener conexiones a estos endpoints.

Estos extremos se contactan en dos situaciones:

* Desde la computadora de un usuario al completar acciones desde el  https://console.bluexp.netapp.com["Consola BlueXP basada en Web"^] que está disponible como software como servicio (SaaS).
* Desde el equipo de un usuario al abrir un navegador web, introduzca la dirección IP del host del conector y, a continuación, inicie sesión y configure el conector. Estos pasos son necesarios si instala manualmente el conector.


[cols="2*"]
|===
| Puntos finales | Específico 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Este es el punto final que ingresa en su navegador web para utilizar la consola basada en web. 


| \https://api.bluexp.netapp.com | La consola basada en web se comunica con este punto final para interactuar con la API para acciones relacionadas con autorización, licencias, suscripciones, credenciales, notificaciones y más. 


| \https://aiq.netapp.com | Necesario para acceder al asesor digital. 


 a| 
Servicios de AWS (amazonaws.com):

* Formación CloudFormation
* Cloud computing elástico (EC2)
* Servicio de gestión de claves (KMS)
* Servicio de token de seguridad (STS)
* Simple Storage Service (S3)

| Necesario para implementar un conector desde BlueXP en AWS. El punto final exacto depende de la región en la que implemente el conector.  https://docs.aws.amazon.com/general/latest/gr/rande.html["Consulte la documentación de AWS para obtener más detalles."] Sugerencia:  https://docs.aws.amazon.com/general/latest/gr/rande.html["Consulte la documentación de AWS para obtener más detalles."] 


| \https://management.azure.com

\https://login.microsoftonline.com | Necesario para implementar un conector desde BlueXP en la mayoría de las regiones de Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Necesario para implementar un conector desde BlueXP en las regiones de Alemania de Azure. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Necesario para desplegar un conector desde BlueXP en las regiones de la Gov de los EE. UU. De Azure. 


| \https://www.googleapis.com | Necesario para desplegar un conector de BlueXP en Google Cloud. 


| \https://signin.b2c.netapp.com | Se requiere actualizar las credenciales del sitio de soporte de NetApp (NSS) o añadir nuevas credenciales de NSS a BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | El explorador Web se conecta a estos extremos para una autenticación de usuario centralizada a través de BlueXP. 


| \https://widget.intercom.io | Para el chat dentro del producto que le permite hablar con el soporte de NetApp. 
|===
Asegúrese de que el Conector tenga acceso a internet saliente para contactar con los puntos finales para las operaciones diarias. Siga los enlaces de la siguiente sección para encontrar la lista de estos puntos finales.

.Información relacionada
* Prepare la conexión a redes para el conector
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configure las redes de AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configure las redes de Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configure las redes de Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Configurar la red local"]


* Prepare las redes para los servicios de BlueXP
+
Consulta la documentación para cada servicio de BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentación de BlueXP"^]


