---
sidebar: sidebar 
permalink: reference-ports-azure.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: El grupo de seguridad de Azure para Connector requiere reglas tanto entrantes como salientes. BlueXP crea automáticamente este grupo de seguridad cuando creas un conector desde BlueXP. Debe configurar este grupo de seguridad para todas las demás opciones de instalación. 
---
= Reglas de grupo de seguridad de conector en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El grupo de seguridad de Azure para Connector requiere reglas tanto entrantes como salientes. BlueXP crea automáticamente este grupo de seguridad cuando creas un conector desde BlueXP. Debe configurar este grupo de seguridad para todas las demás opciones de instalación.



== Reglas de entrada

[cols="3*"]
|===
| Protocolo | Puerto | Específico 


| SSH | 22 | Proporciona acceso SSH al host de Connector 


| HTTP | 80  a| 
* Proporciona acceso HTTP desde navegadores web de cliente al local interfaz de usuario
* Se utiliza durante el proceso de actualización de Cloud Volumes ONTAP




| HTTPS | 443 | Ofrece acceso HTTPS desde los navegadores web del cliente a la interfaz de usuario local y conexiones desde la instancia de clasificación de BlueXP 


| TCP | 3128 | Proporciona a Cloud Volumes ONTAP acceso a Internet para enviar mensajes de AutoSupport al soporte de NetApp. Debe abrir manualmente este puerto después de la implementación. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-verify-autosupport.html["Obtenga información sobre cómo se utiliza el conector como proxy para los mensajes de AutoSupport"^] 
|===


== Reglas de salida

El grupo de seguridad predefinido para el conector abre todo el tráfico saliente. Si eso es aceptable, siga las reglas básicas de la salida. Si necesita más reglas rígidas, utilice las reglas avanzadas de salida.



=== Reglas de salida básicas

El grupo de seguridad predefinido para el conector incluye las siguientes reglas de salida.

[cols="3*"]
|===
| Protocolo | Puerto | Específico 


| Todos los TCP | Todo | Todo el tráfico saliente 


| Todas las UDP | Todo | Todo el tráfico saliente 
|===


=== Reglas salientes avanzadas

Si necesita reglas rígidas para el tráfico saliente, puede utilizar la siguiente información para abrir sólo los puertos necesarios para la comunicación saliente por parte del conector.


NOTE: La dirección IP de origen es el host del conector.

[cols="5*"]
|===
| Servicio | Protocolo | Puerto | Destino | Específico 


| Llamadas API y AutoSupport | HTTPS | 443 | LIF de gestión de clústeres de ONTAP y Internet saliente | Llamadas API a Azure, a ONTAP, a la clasificación de BlueXP y al enviar mensajes de AutoSupport a NetApp 


| Llamadas API | TCP | 8080 | Clasificación de BlueXP | Sondee la instancia de clasificación de BlueXP durante la puesta en marcha 


| DNS | UDP | 53 | DNS | Utilizado para resolver DNS por BlueXP 
|===