---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Asignar roles de plataforma a los usuarios para otorgar permisos para realizar tareas de administración en BlueXP, asignar roles, agregar usuarios, crear conectores y administrar federaciones. 
---
= Funciones de acceso a la plataforma BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Asignar roles de plataforma a los usuarios para otorgar permisos para realizar tareas de administración en BlueXP, asignar roles, agregar usuarios, crear conectores y administrar federaciones.

.Ejemplo de roles de organización en BlueXP  para una organización multinacional grande
XYZ Corporation organiza el acceso al almacenamiento de datos por región (América del Norte, Europa y Asia-Pacífico), proporcionando control regional con supervisión centralizada.

El *administrador de la organización* en BlueXP de XYZ Corporation crea una organización inicial y carpetas separadas para cada región.  El administrador de carpeta o proyecto de cada región organiza los proyectos (con los recursos asociados) dentro de la carpeta de la región.

Los administradores regionales con el rol de *Administrador de carpeta o proyecto* administran activamente sus carpetas agregando recursos y usuarios.  Estos administradores regionales también pueden agregar, eliminar o cambiar el nombre de las carpetas y los proyectos que administran.  El *administrador de la organización* hereda los permisos para cualquier recurso nuevo, lo que mantiene la visibilidad del uso del almacenamiento en toda la organización.

Dentro de la misma organización, a un usuario se le asigna el rol de *administrador de federación* para administrar la federación de la organización con su IdP corporativo.  Este usuario puede agregar o eliminar organizaciones federadas, pero no puede administrar usuarios ni recursos dentro de la organización.  El *Administrador de la organización* asigna a un usuario el rol de *Visor de la federación* para verificar el estado de la federación y ver las organizaciones federadas.

Las siguientes tablas indican las acciones que cada rol de la plataforma BlueXP puede realizar.



== Roles de administración de la organización

[cols="2,1,1"]
|===
| Tarea | Administrador de la organización | Administrador de carpetas o proyectos 


| Crear conectores | Sí | No 


| Crear, modificar o suprimir entornos de trabajo (añadir o detectar nuevos recursos mediante el lienzo de BlueXP ) | Sí | Sí 


| Cree carpetas y proyectos, incluida la eliminación | Sí | No 


| Cambie el nombre de las carpetas y proyectos existentes | Sí | Sí 


| Asigne roles y añada usuarios | Sí | Sí 


| Asociar recursos a carpetas y proyectos | Sí | Sí 


| Asociar conectores a carpetas y proyectos | Sí | No 


| Eliminar conectores de carpetas y proyectos | Sí | No 


| Administrar conectores (editar certificados, configuración, etc.) | Sí | No 


| Gestione credenciales desde Configuración > Credenciales | Sí | Sí 


| Crear, administrar y visualizar federaciones | Sí | No 


| Regístrese para recibir soporte y enviar casos a través de BlueXP | Sí | Sí 


| Utilizar servicios de datos | Sí | Sí 


| Ver la línea de tiempo y las notificaciones de BlueXP | Sí | Sí 
|===


== Roles de la federación

[cols="2,1,1"]
|===
| Tarea | Administración de la federación | Visor de la Federación 


| Crear una federación | Sí | No 


| Verificar un dominio | Sí | No 


| Agregar un dominio a una federación | Sí | No 


| Deshabilitar y eliminar federaciones | Sí | No 


| Federaciones de pruebas | Sí | No 


| Ver federaciones y sus detalles | Sí | Sí 
|===