---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Cuando empieces a usar BlueXP, asegúrate de que tus redes permitan el acceso a extremos específicos desde la consola BlueXP. Dependiendo de cómo tengas pensado utilizar BlueXP, es posible que también necesites configurar la conexión a redes para un conector y para servicios específicos de BlueXP. 
---
= Prepare la red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando empieces a usar BlueXP, asegúrate de que tus redes permitan el acceso a extremos específicos desde la consola BlueXP. Dependiendo de cómo tengas pensado utilizar BlueXP, es posible que también necesites configurar la conexión a redes para un conector y para servicios específicos de BlueXP.



== Prepare la red para que los usuarios puedan acceder a la consola BlueXP

A medida que utiliza la consola basada en Web BlueXP que se proporciona a través de la capa SaaS, se pone en contacto con varios extremos para completar las tareas de gestión de datos. La máquina que ejecuta el explorador Web debe tener conexiones con estos extremos.

[cols="2*"]
|===
| Puntos finales | Específico 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Su navegador web se pone en contacto con estas URL cuando utiliza la consola basada en web de BlueXP. 


 a| 
Servicios de AWS (amazonaws.com):

* Formación CloudFormation
* Cloud computing elástico (EC2)
* Servicio de gestión de claves (KMS)
* Servicio de token de seguridad (STS)
* Simple Storage Service (S3)

| Necesario para implementar un conector desde BlueXP en AWS. El extremo exacto depende de la región en la que se despliega el conector. https://docs.aws.amazon.com/general/latest/gr/rande.html["Consulte la documentación de AWS para obtener más detalles."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Necesario para implementar un conector desde BlueXP en la mayoría de las regiones de Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Necesario para implementar un conector desde BlueXP en las regiones de Alemania de Azure. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Necesario para desplegar un conector desde BlueXP en las regiones de la Gov de los EE. UU. De Azure. 


| \https://www.googleapis.com | Necesario para desplegar un conector de BlueXP en Google Cloud. 


| \https://signin.b2c.netapp.com | Se requiere actualizar las credenciales del sitio de soporte de NetApp (NSS) o añadir nuevas credenciales de NSS a BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | El explorador Web se conecta a estos extremos para una autenticación de usuario centralizada a través de BlueXP. 


| \https://widget.intercom.io | Si busca un chat integrado en los productos que le permita hablar con expertos en cloud de NetApp. 
|===
Más allá de estos puntos finales, también debe asegurarse de que Connector tiene acceso a Internet saliente para contactar puntos finales específicos para las operaciones diarias. Puede encontrar la lista de estos puntos finales siguiendo los enlaces de la siguiente sección.



== Prepare la conexión en red para un conector

La forma en que prepare su red para un conector depende de dónde planea instalar el conector, que puede estar en la nube o en sus instalaciones. Para obtener información detallada sobre los requisitos de red del conector, consulte las páginas siguientes:

* link:task-set-up-networking-aws.html["Configure las redes de AWS"]
* link:task-set-up-networking-azure.html["Configure las redes de Azure"]
* link:task-set-up-networking-google.html["Configure las redes de Google Cloud"]
* link:task-set-up-networking-on-prem.html["Configure las redes en las instalaciones"]




== Prepare las redes para los servicios de BlueXP

Para empezar a usar BlueXP, debes asegurarte de haber cumplido los requisitos de red de los servicios de BlueXP que planeas utilizar. Para obtener más información, consulte la documentación de cada servicio.

https://docs.netapp.com/us-en/bluexp-family/["Documentación de BlueXP"^]
