---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: La gestión de identidades y accesos de BlueXP  incluye varios roles predefinidos que puede asignar a los miembros de la organización. 
---
= Roles y permisos predefinidos de IAM de BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestión de identidades y accesos (IAM) de BlueXP  incluye varios roles predefinidos que se pueden asignar a los miembros de la organización en diferentes niveles de la jerarquía de recursos. Antes de asignar estos roles, debe comprender los permisos que incluye cada rol.



== Funciones de la plataforma

BlueXP  IAM incluye dos funciones de plataforma: Administrador de organización y Administrador de carpetas o proyectos. La principal diferencia entre los dos roles de la plataforma IAM de BlueXP  es Scope. La función de administrador de organización tiene permisos en todas las carpetas y proyectos, mientras que la carpeta o el administrador del proyecto sólo tienen permisos en la carpeta o el proyecto al que se han asignado.

La función de administrador de carpeta o proyecto no puede crear conectores.

Permisos::


[cols="24,19,19"]
|===
| Tarea | Administrador de la organización | Administrador de carpeta o proyecto 


| Crear conectores | Sí | No 


| Crear, modificar o suprimir entornos de trabajo (añadir o detectar nuevos recursos mediante el lienzo de BlueXP ) | Sí | Sí 


| Cree proyectos/carpetas, incluido el cambio de nombre, la eliminación y la edición | Sí | Sí 


| Asigne roles y añada usuarios | Sí | Sí 


| Asociar recursos y conectores a carpetas y proyectos | Sí | Sí 


| Gestione credenciales desde Configuración > Credenciales | Sí | Sí 


| Consulta la línea de tiempo de BlueXP  | Sí | Sí 


| Utilizar los servicios BlueXP  | Sí | Sí 


| Registre BlueXP  para obtener soporte y enviar casos | Sí | Sí 
|===
Ejemplo de roles de organización en BlueXP  para una organización multinacional grande:: XYZ Corporation, una empresa multinacional, tiene como objetivo segregar el acceso a recursos de almacenamiento de datos basados en regiones geográficas: Norteamérica, Europa y Asia Pacífico. Quieren que cada región tenga un control exclusivo sobre sus recursos mientras mantienen una supervisión centralizada.
+
--
Para lograr esto, una persona que tiene asignada la función de administrador de la organización en BlueXP  de Xyz Corporation crea un entorno de trabajo inicial y, a continuación, crea carpetas separadas en BlueXP  para cada región. La carpeta de cada región contiene proyectos (con recursos asociados) relacionados con esa región. El administrador de la organización asigna a un usuario de BlueXP  en cada región respectiva la función de administrador de carpeta/proyecto.

Una vez completada la configuración inicial, los administradores regionales con la función de administrador de carpeta o proyecto pueden crear nuevos entornos de trabajo y agregar usuarios dentro de sus regiones. Estos administradores regionales también pueden agregar/eliminar/cambiar el nombre de las carpetas y los proyectos a los que están asignados. El administrador de la organización hereda permisos para cualquier nuevo entorno de trabajo o recursos, manteniendo la visibilidad del uso del almacenamiento en toda la organización.

--




== Roles de servicios de datos

Los roles de servicios de datos pueden completar sus tareas en cualquier proyecto o carpeta.



=== Administrador de SnapCenter

Descripción:: Ofrece la posibilidad de realizar backups de snapshots de clústeres de ONTAP en las instalaciones mediante backup y recuperación de datos de BlueXP  en aplicaciones.
Permisos:: Un miembro que tenga este rol puede realizar las siguientes acciones en BlueXP :
+
--
* Realice cualquier acción desde Copia de seguridad y recuperación > Aplicaciones
* Gestione todos los entornos de trabajo en los proyectos y carpetas para los que tienen permisos
* Utilizar todos los servicios BlueXP 


--




=== Visor de clasificación

Descripción:: Proporciona la posibilidad de ver los resultados de la exploración de clasificación de BlueXP .
Permisos:: Ver información de cumplimiento y generar informes para los recursos a los que tienen permiso para acceder. Estos usuarios no pueden activar o desactivar el análisis de volúmenes, bloques o esquemas de base de datos.
+
--
No hay otras acciones disponibles para un miembro que tenga este rol.

--




== Enlaces relacionados

* link:concept-identity-and-access-management.html["Obtenga más información sobre la gestión de identidades y accesos de BlueXP "]
* link:task-iam-get-started.html["Comience a usar BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gestionar miembros de BlueXP  y sus permisos"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Obtenga más información sobre la API para IAM de BlueXP "^]

