---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: La gestión de identidades y accesos de BlueXP  incluye varios roles predefinidos que puede asignar a los miembros de la organización. 
---
= Roles y permisos predefinidos de IAM de BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestión de identidades y accesos (IAM) de BlueXP  incluye varios roles predefinidos que se pueden asignar a los miembros de la organización en diferentes niveles de la jerarquía de recursos. Antes de asignar estos roles, debe comprender los permisos que incluye cada rol.



== Administrador de la organización

Descripción:: Proporciona control total de toda la organización de BlueXP .
Permisos:: Un miembro que tenga este rol puede completar todas las acciones en BlueXP .




== Administrador de carpetas o proyectos

Descripción:: Proporciona un control total de uno o más proyectos y carpetas.
+
--
Tenga en cuenta que si asigna este rol en el nivel de carpeta, el miembro tiene permisos para todos los proyectos asociados a esa carpeta.

--
Permisos:: Un miembro que tenga este rol puede realizar las siguientes acciones en BlueXP :
+
--
* Gestione todos los entornos de trabajo en los proyectos y carpetas para los que tienen permisos
* Utilizar todos los servicios BlueXP 
* Desde BlueXP  IAM, un administrador de una carpeta puede administrar las carpetas, los proyectos y los recursos que son hijos de esa carpeta:
+
** Agregue carpetas o proyectos dentro de la carpeta
** Editar carpetas y proyectos: Sus nombres, recursos asociados y acceso de miembros
** Suprimir carpetas y proyectos
** Agregue una cuenta de usuario y asocie un rol a nivel de carpeta o proyecto
** Asociar un conector a una carpeta o proyecto
** Agregue un rol a un miembro en el nivel de carpeta o proyecto
** Ver recursos asociados a carpetas y proyectos
** Asociar recursos visibles a carpetas o proyectos adicionales
** Disociar un recurso de una carpeta o proyecto


* Desde BlueXP  IAM, un administrador de un proyecto puede administrar ese proyecto y sus recursos asociados de la siguiente manera:
+
** Edite el proyecto: Su nombre, recursos asociados y acceso de miembros
** Agregue una cuenta de usuario y asocie un rol en el nivel de proyecto
** Asocie un conector a un proyecto, si el miembro tiene permisos de administrador a otros proyectos que tienen otros conectores asociados
** Agregue un rol a un miembro en el nivel de proyecto
** Ver los recursos asociados al proyecto
** Asocie recursos al proyecto, si el miembro tiene permisos de administrador a otros proyectos que tienen otros recursos asociados
** Disociar un recurso del proyecto
** Elimine el proyecto


* Gestione credenciales desde Configuración > Credenciales
* Consulta la línea de tiempo de BlueXP 
* Registre BlueXP  para obtener soporte y enviar casos


--




== Administrador de SnapCenter

Descripción:: Ofrece la posibilidad de realizar backups de snapshots de clústeres de ONTAP en las instalaciones mediante backup y recuperación de datos de BlueXP  en aplicaciones.
Permisos:: Un miembro que tenga este rol puede realizar las siguientes acciones en BlueXP :
+
--
* Realice cualquier acción desde Copia de seguridad y recuperación > Aplicaciones
* Gestione todos los entornos de trabajo en los proyectos y carpetas para los que tienen permisos
* Utilizar todos los servicios BlueXP 


--




== Visor de clasificación

Descripción:: Proporciona la posibilidad de ver los resultados de la exploración de clasificación de BlueXP .
Permisos:: Ver información de cumplimiento y generar informes para los recursos a los que tienen permiso para acceder. Estos usuarios no pueden activar o desactivar el análisis de volúmenes, bloques o esquemas de base de datos.
+
--
No hay otras acciones disponibles para un miembro que tenga este rol.

--




== Enlaces relacionados

* link:concept-identity-and-access-management.html["Obtenga más información sobre la gestión de identidades y accesos de BlueXP "]
* link:task-iam-get-started.html["Comience a usar BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gestionar miembros de BlueXP  y sus permisos"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Obtenga más información sobre la API para IAM de BlueXP "^]

