---
sidebar: sidebar 
permalink: reference-host-requirements-on-prem.html 
keywords: cpu requirements, ram requirements, on prem requirements, on prem host requirements, connector host requirements 
summary: El software del conector debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de puerto, etc. Asegúrese de que el host cumple estos requisitos antes de instalar el conector. 
---
= Consulte los requisitos del host de Connector para las instalaciones en el entorno local
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software del conector debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de puerto, etc. Asegúrese de que el host cumple estos requisitos antes de instalar el conector.

Host dedicado:: El conector no es compatible con un host compartido con otras aplicaciones. El host debe ser un host dedicado.
Sistemas operativos compatibles::
+
--
* Sistema operativo Ubuntu 22,04
* CentOS 7.6, 7.7, 7.8 y 7.9
* Red Hat Enterprise Linux 7,6, 7,7, 7,8 y 7,9
+
El host debe estar registrado con Red Hat Subscription Management. Si no está registrado, el host no puede acceder a los repositorios para actualizar el software de terceros necesario durante la instalación del conector.

+
El conector es compatible con las versiones en inglés de estos sistemas operativos.



--
Hipervisor:: Se requiere un hipervisor con configuración básica o alojado certificado para ejecutar Ubuntu, CentOS o Red Hat Enterprise Linux.
+
--
https://["Red Hat Solution: ¿Qué hipervisores están certificados para ejecutar Red Hat Enterprise Linux?"^]

--
CPU:: 4 núcleos o 4 vCPU
RAM:: 14 GB
Espacio en disco en /opt:: Debe haber 100 GIB de espacio disponibles
Espacio en disco en /var:: Debe haber 20 GIB de espacio disponibles
Motor Docker:: Se requiere Docker Engine versión 19.3.1 o posterior en el host antes de instalar el conector. https://["Ver las instrucciones de instalación"^]

