---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: Las funciones Administrador de cuentas, Administrador de área de trabajo, Visor de cumplimiento y Administrador de SnapCenter proporcionan permisos específicos a los usuarios. Puedes asignar uno de estos roles cuando asocias un nuevo usuario a tu cuenta de BlueXP. 
---
= Roles de usuario
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando utilice BlueXP  en modo restringido o en modo privado, utilizará una cuenta _BlueXP _ para administrar usuarios. Puede proporcionar permisos específicos a los usuarios de su cuenta seleccionando entre las siguientes funciones: Administrador de cuenta, Administrador de espacio de trabajo, Visor de cumplimiento y Administrador de SnapCenter

Si usas BlueXP  en modo estándar, no tendrás una cuenta de BlueXP . En su lugar, dispondrá de una organización _BlueXP _ que gestionará mediante la administración de identidades y accesos (IAM) de BlueXP .

* link:concept-identity-and-access-management.html["Obtenga más información sobre BlueXP  IAM"]
* link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"]


[cols="24,19,19,19,19"]
|===
| Tarea | Administrador de cuentas | Administrador de área de trabajo | Visor de cumplimiento de normativas | Administrador de SnapCenter 


| Crear conectores | Sí | No | No | No 


| Gestionar entornos de trabajo | Sí | Sí | No | Sí 


| Activar servicios en entornos de trabajo | Sí | Sí | No | Sí 


| Utilizar los servicios BlueXP  | Sí | Sí | No | Sí 


| Eliminar entornos de trabajo de un espacio de trabajo | Sí | Sí | No | No 


| Eliminar entornos de trabajo | Sí | Sí | No | No 


| Ver el estado de replicación de datos | Sí | Sí | No | No 


| Visualice la línea de tiempo | Sí | Sí | No | No 


| Cambiar entre espacios de trabajo | Sí | Sí | Sí | Sí 


| Consulta los resultados del análisis de clasificación de BlueXP | Sí | Sí | Sí | No 


| Reciba el informe de Cloud Volumes ONTAP | Sí | No | No | No 


| Administrar cuentas de BlueXP | Sí | No | No | No 


| Gestionar credenciales | Sí | Sí | No | No 


| Modificar la configuración de BlueXP | Sí | Sí | No | No 


| Consulte y gestione la consola de soporte | Sí | Sí | No | No 
|===
.Enlace relacionado
link:task-managing-netapp-accounts.html["Administre su cuenta de BlueXP"]
