---
sidebar: sidebar 
permalink: reference-connector-maint-console.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy 
summary: Utilice la Consola de mantenimiento para configurar el Conector para utilizar un servidor proxy transparente. 
---
= Consola de mantenimiento del conector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar la Consola de mantenimiento para configurar el Conector para utilizar un servidor proxy transparente.



== Acceda a la Consola de mantenimiento

Puede acceder a la Consola de mantenimiento desde el host del conector. Desplácese al siguiente directorio:

[source, CLI]
----
/opt/application/netapp/service-manager-2/connector-maint-console
----


== Comandos de proxy transparentes

La consola de mantenimiento proporciona comandos para configurar el conector para utilizar un servidor proxy transparente.



=== Ver la configuración actual del proxy transparente

Para ver la configuración actual del proxy transparente, utilice el siguiente comando:

[source, CLI]
----
./connector-maint-console proxy get
----


=== Agregar un servidor proxy transparente

Para agregar un servidor proxy transparente, utilice el siguiente comando, donde  `/home/ubuntu/myCA1.pem` Es la ruta al archivo de certificado del servidor proxy. El archivo de certificado debe estar en formato PEM.

[source, CLI]
----
./connector-maint-console proxy add -c /home/ubuntu/myCA1.pem
----
Asegúrese de que el archivo de certificado esté en el mismo directorio que el comando o especifique la ruta completa al archivo de certificado.



=== Actualizar el certificado para un servidor proxy transparente

Para actualizar el certificado de un servidor proxy transparente, utilice el siguiente comando, donde  `/home/ubuntu/myCA1.pem` Es la ruta al nuevo archivo de certificado del servidor proxy. El archivo de certificado debe estar en formato PEM.

[source, CLI]
----
./connector-maint-console proxy update -c /home/ubuntu/myCA1.pem
----
Asegúrese de que el archivo de certificado esté en el mismo directorio que el comando o especifique la ruta completa al archivo de certificado.



=== Eliminar un servidor proxy transparente

Para eliminar el servidor proxy transparente, utilice el siguiente comando:

[source, CLI]
----
./connector-maint-console proxy remove
----


=== Ver ayuda para cualquier comando

Para ver la ayuda de cualquier comando, agregue  `--help` al comando. Por ejemplo, para ver la ayuda del  `proxy add` Comando, utilice el siguiente comando:

[source, CLI]
----
./connector-maint-console proxy add --help
----