---
sidebar: sidebar 
permalink: task-create-account.html 
keywords: create account, account, create, create another account, tenancy account, tenancy, tenancy account creation 
summary: Cuando se registra en BlueXP, se le pide que cree una cuenta para su organización. Esta cuenta puede ser todo lo que necesite, pero si su negocio requiere varias cuentas, tendrá que crear cuentas adicionales con la API de tenancy. 
---
= Cree otra cuenta de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se registra en BlueXP, se le pide que cree una cuenta para su organización. Esta cuenta puede ser todo lo que necesite, pero si su negocio requiere varias cuentas, tendrá que crear cuentas adicionales con la API de tenancy.

Utilice la siguiente llamada a la API para crear una cuenta de BlueXP adicional:

PUBLICAR `/tenancy/account/{accountName}`

Si desea habilitar el modo restringido, debe incluir lo siguiente en el cuerpo de la solicitud:

[source, JSON]
----
{
  "isSaasDisabled": true
}
----

NOTE: No se puede cambiar la configuración del modo restringido después de que BlueXP cree la cuenta. No se puede activar el modo restringido más adelante y no se puede desactivar más adelante. Se debe establecer en el momento de crear la cuenta.

https://docs.netapp.com/us-en/cloud-manager-automation/tenancy/post-tenancy-account-.html["Aprenda a usar esta llamada API"^]

.Enlaces relacionados
* link:concept-netapp-accounts.html["Obtenga más información sobre las cuentas de BlueXP"]
* link:concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"]

