---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Después de registrarse en BlueXP, puede iniciar sesión desde su navegador Web a través de la consola basada en Web. 
---
= Iniciar sesión en BlueXP (modo estándar)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de registrarse en BlueXP, puede iniciar sesión desde la consola basada en Web.

.Opciones de inicio de sesión
Puede iniciar sesión en la consola basada en Web de BlueXP mediante una de las siguientes opciones:

* Sus credenciales existentes del sitio de soporte de NetApp (NSS)
* Un inicio de sesión en el cloud de NetApp con su dirección de correo electrónico y una contraseña
* Una conexión federada
+
Puede utilizar el inicio de sesión único para iniciar sesión con credenciales del directorio corporativo (identidad federada). link:concept-federation.html["Aprenda a usar la federación de identidades con BlueXP"].



.Pasos
. Abra un explorador web y vaya al https://console.bluexp.netapp.com["Consola BlueXP"^]
. En la página *Iniciar sesión*, introduzca la dirección de correo electrónico asociada a su inicio de sesión.
. En función del método de autenticación asociado a su inicio de sesión, se le pedirá que introduzca sus credenciales:
+
** Credenciales de cloud de NetApp: Introduzca su contraseña
** Federated user: Introduzca las credenciales de identidad federadas
** Cuenta del sitio de soporte de NetApp: Introduzca sus credenciales del sitio de soporte de NetApp




.Resultado
Ya ha iniciado sesión y puede empezar a utilizar BlueXP para gestionar su infraestructura multicloud híbrida.
