---
sidebar: sidebar 
permalink: task-log-in-restricted-mode.html 
keywords: logging in, log in, sign in, signing in, restricted mode, restricted mode log in, local log in, connector log in, log in connector 
summary: Cuando utilizas BlueXP en modo restringido, tendrás que iniciar sesión en la consola de BlueXP desde la interfaz de usuario que se ejecuta localmente en Connector. 
---
= Iniciar sesión en BlueXP (modo restringido)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando utilizas BlueXP en modo restringido, tendrás que iniciar sesión en la consola de BlueXP desde la interfaz de usuario que se ejecuta localmente en Connector.

.Opciones de inicio de sesión
BlueXP permite iniciar sesión con una de las siguientes opciones cuando su cuenta está configurada en modo restringido:

* Un inicio de sesión en el cloud de NetApp con su dirección de correo electrónico y una contraseña
* Una conexión federada
+
Puede utilizar el inicio de sesión único para iniciar sesión con credenciales del directorio corporativo (identidad federada). link:concept-federation.html["Aprenda a usar la federación de identidades con BlueXP"].



.Pasos
. Abra un explorador web e introduzca la siguiente URL:
+
https://_ipaddress_[]

+
_Ipaddress_ puede ser localhost, una dirección IP privada o una dirección IP pública, dependiendo de la configuración del host en el que instaló el conector. Por ejemplo, es posible que necesite introducir una dirección IP privada de un host que tenga una conexión con el host Connector.

. Introduzca su nombre de usuario y contraseña para iniciar sesión.


.Resultado
Ya ha iniciado sesión y puede empezar a utilizar BlueXP para gestionar su infraestructura multicloud híbrida.
