---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector 
summary: El mantenimiento del sistema operativo en el host del conector es responsabilidad suya. Por ejemplo, debe aplicar actualizaciones de seguridad al sistema operativo en el host del conector siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo. 
---
= Mantener la VM Connector y el sistema operativo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El mantenimiento del sistema operativo en el host del Conector es responsabilidad del cliente. Por ejemplo, debe aplicar actualizaciones de seguridad al sistema operativo del host del Conector siguiendo los procedimientos estándar de su empresa para la distribución de sistemas operativos.


TIP: Si tiene un conector existente, debe tener en cuenta link:reference-connector-operating-system-changes.html["Cambios en los sistemas operativos Linux admitidos"].



== Parches del sistema operativo y el conector

No es necesario detener ningún servicio en el host de Connector al aplicar parches de seguridad del sistema operativo.



== Tipo de máquina virtual o instancia

Si creaste un Connector directamente desde BlueXP, BlueXP implementó una instancia de máquina virtual en tu proveedor de nube con una configuración predeterminada. Después de crear el conector, no debe cambiar a una instancia de VM más pequeña que tenga menos CPU o RAM.

Los requisitos de CPU y RAM son los siguientes:

CPU:: 8 núcleos o 8 vCPU
RAM:: 32GB


link:reference-connector-default-config.html["Obtenga información sobre la configuración predeterminada para el conector"].



== Parada e inicio de Connector VM

Si necesita detener y, a continuación, iniciar Connector VM, debe hacerlo desde la consola de su proveedor de cloud o mediante los procedimientos estándar para la gestión en las instalaciones.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["Tenga en cuenta que el conector debe estar operativo en todo momento"].



== Conéctese a la máquina virtual de Linux

Si necesita conectarse a la VM de Linux en la que se ejecuta el conector, puede hacerlo utilizando las opciones de conectividad disponibles de su proveedor de cloud.

AWS:: Al crear la instancia de Connector en AWS, proporcionó una clave de acceso y una clave secreta de AWS. Es posible usar este par de claves para SSH a la instancia. El nombre de usuario para la instancia de Linux EC2 es ubuntu (para los conectores creados antes de mayo de 2023, el nombre de usuario era EC2-user).
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs: Conéctese a su instancia de Linux"^]

--
Azure:: Cuando creó la máquina virtual de Connector en Azure, especificó un nombre de usuario y optó por autenticarse con una contraseña o clave pública SSH. Utilice el método de autenticación que ha elegido para conectarse a la máquina virtual.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs: SSH en su máquina virtual"^]

--
Google Cloud:: No puede especificar un método de autenticación al crear un conector en Google Cloud. Sin embargo, puede conectarse a la instancia de VM de Linux mediante Google Cloud Console o Google Cloud CLI (gcloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: Conexión a equipos virtuales Linux"^]

--




== Cambiar la dirección IP de un conector

Si es necesario para su empresa, puede cambiar la dirección IP interna y la dirección IP pública de la instancia de conector que asigna automáticamente su proveedor de cloud.

.Pasos
. Siga las instrucciones del proveedor de cloud para cambiar la dirección IP local o la dirección IP pública (o ambas) de la instancia de Connector.
. Si ha cambiado la dirección IP pública y necesita conectarse a la interfaz de usuario local que se ejecuta en el conector, reinicie la instancia del conector para registrar la nueva dirección IP con BlueXP.
. Si cambió la dirección IP privada, actualice la ubicación de copia de seguridad de los archivos de configuración de Cloud Volumes ONTAP para que las copias de seguridad se envíen a la nueva dirección IP privada del conector.
+
Deberá actualizar la ubicación de copia de seguridad de cada sistema Cloud Volumes ONTAP.

+
.. En la interfaz de línea de comandos de Cloud Volumes ONTAP, establezca el nivel de privilegio en advanced:
+
[source, cli]
----
set -privilege advanced
----
.. Ejecute el siguiente comando para mostrar el destino de backup actual:
+
[source, cli]
----
system configuration backup settings show
----
.. Ejecute el siguiente comando para actualizar la dirección IP del destino de copia de seguridad:
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== Editar los URI de un conector

Agregue y elimine el identificador uniforme de recursos (URI) de un conector.

.Pasos
. Seleccione la lista desplegable *conector* del encabezado BlueXP.
. Seleccione *gestionar conectores*.
. Expanda la barra *Connector URI* para ver los URI de un conector.
. Expanda la barra *Connector URI* para ver los URI de un conector.
. Agregue y elimine URIs y, a continuación, seleccione *aplicar*.

