---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector, notifications, connector health, connector disk space, connector cpu usage, connector ram usage, connector vm, connector ip address, connector uri 
summary: El mantenimiento del sistema operativo en el host del conector es responsabilidad suya. Por ejemplo, debe aplicar actualizaciones de seguridad al sistema operativo en el host del conector siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo. 
---
= Mantener la VM Connector y el sistema operativo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El mantenimiento del sistema operativo en el host del Conector es responsabilidad del cliente. Por ejemplo, debe aplicar actualizaciones de seguridad al sistema operativo del host del Conector siguiendo los procedimientos estándar de su empresa para la distribución de sistemas operativos.


TIP: Si tiene un conector existente, debe tener en cuenta link:reference-connector-operating-system-changes.html["Cambios en los sistemas operativos Linux admitidos"].



== Parches del sistema operativo y el conector

Aplicar parches de seguridad del sistema operativo sin detener los servicios del host del conector.



== Tipo de máquina virtual o instancia

Si crea un conector desde BlueXP, se implementará una instancia de máquina virtual en su proveedor de nube con una configuración predeterminada. Después de crear el conector, no cambie a una instancia de máquina virtual más pequeña con menos CPU o RAM.

La siguiente tabla enumera los requisitos de CPU y RAM:

CPU:: 8 núcleos o 8 vCPU
RAM:: 32GB


link:reference-connector-default-config.html["Obtenga información sobre la configuración predeterminada para el conector"].



== Monitorear el conector

BlueXP le notifica cuando la máquina virtual del conector presenta problemas, incluyendo problemas de espacio en disco, RAM y CPU. Supervise estas notificaciones en el Centro de notificaciones de BlueXP o configure notificaciones por correo electrónico. Los aumentos ocasionales en el uso de espacio en disco, memoria o CPU son normales, pero si ocurren con frecuencia, debe tomar medidas para solucionarlos.

BlueXP le notifica cuando un recurso del Conector (CPU, RAM o espacio en disco) supera el 90 % de su capacidad total durante 30 minutos consecutivos. Posteriormente, si el uso del recurso cae por debajo de ese umbral, la notificación se muestra como resuelta (verde) en el Centro de notificaciones.


NOTE: Trabaje con el soporte de NetApp si tiene preguntas sobre cómo modificar su máquina virtual Connector.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center["Leer más."^]

[cols="47,47"]
|===
| Notificación | Es necesario actuar 


| El espacio en disco es demasiado alto | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["Revise el artículo de la base de conocimientos de NetApp"^]. 


| El uso de la CPU es demasiado alto | Aumente el tamaño de la CPU de la máquina virtual del conector en su hiperescalador o en su entorno local, según dónde la haya instalado. Como alternativa, cree conectores adicionales y distribuya la carga de trabajo entre varios. El uso de RAM puede variar según su entorno, las cargas de trabajo de ONTAP , la cantidad de sistemas Cloud Volumes ONTAP y los servicios de datos que utilice. 


| El uso de RAM es demasiado alto | Aumente la RAM de la máquina virtual del conector en su hiperescalador o en las instalaciones locales, según dónde la haya instalado. Como alternativa, cree conectores adicionales y distribuya la carga de trabajo entre varios. El uso de RAM puede variar según su entorno, las cargas de trabajo de ONTAP , la cantidad de sistemas Cloud Volumes ONTAP y los servicios de datos que utilice. 
|===


== Parada e inicio de Connector VM

Si es necesario, detenga e inicie la máquina virtual Connector mediante la consola de su proveedor de nube o los procedimientos locales estándar.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["Tenga en cuenta que el conector debe estar operativo en todo momento"].



== Conéctese a la máquina virtual de Linux

Si necesita conectarse a la máquina virtual Linux en la que se ejecuta el conector, utilice las opciones de conectividad de su proveedor de nube.

AWS:: Al crear la instancia del Conector en AWS, proporcione una clave de acceso y una clave secreta de AWS. Es posible usar este par de claves para SSH a la instancia. Use el nombre de usuario "ubuntu" para la instancia EC2 Linux. Para los Conectores creados antes de mayo de 2023, use el nombre de usuario "ec2-user".
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs: Conéctese a su instancia de Linux"^]

--
Azure:: Cuando crea la máquina virtual del conector en Azure, especifica un nombre de usuario y elige autenticarse con una contraseña o una clave pública SSH. Utilice el método de autenticación que ha elegido para conectarse a la máquina virtual.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs: SSH en su máquina virtual"^]

--
Google Cloud:: No puede especificar un método de autenticación al crear un conector en Google Cloud. Sin embargo, puede conectarse a la instancia de VM de Linux mediante Google Cloud Console o Google Cloud CLI (gcloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: Conexión a equipos virtuales Linux"^]

--




== Cambiar la dirección IP de un conector

Puede cambiar las direcciones IP internas y públicas de la instancia del Conector asignada por su proveedor de nube si es necesario.

.Pasos
. Siga las instrucciones del proveedor de cloud para cambiar la dirección IP local o la dirección IP pública (o ambas) de la instancia de Connector.
. Reinicie la instancia del Conector para registrar una nueva dirección IP pública con BlueXP.
. Si cambió la dirección IP privada, actualice la ubicación de copia de seguridad de los archivos de configuración de Cloud Volumes ONTAP para que las copias de seguridad se envíen a la nueva dirección IP privada del conector.
+
Actualice la ubicación de la copia de seguridad para cada sistema Cloud Volumes ONTAP .

+
.. En la interfaz de línea de comandos de Cloud Volumes ONTAP, establezca el nivel de privilegio en advanced:
+
[source, cli]
----
set -privilege advanced
----
.. Ejecute el siguiente comando para mostrar el destino de backup actual:
+
[source, cli]
----
system configuration backup settings show
----
.. Ejecute el siguiente comando para actualizar la dirección IP del destino de copia de seguridad:
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== Editar los URI de un conector

Puede agregar y eliminar el Identificador uniforme de recursos (URI) para un conector.

.Pasos
. Seleccione la lista desplegable *conector* del encabezado BlueXP.
. Seleccione *gestionar conectores*.
. Expande la barra *URI del conector* para ver los URI del conector.
. Agregue y elimine URIs y, a continuación, seleccione *aplicar*.

