---
sidebar: sidebar 
permalink: task-provide-permissions-google.html 
keywords: google cloud permissions, permissions, gcp permissions, service account, gcp service account 
summary: Si instaló manualmente el software Connector en su propio host Linux, debe proporcionar BlueXP los permisos que configuró anteriormente. Al proporcionar los permisos, BlueXP podrá gestionar tus datos y la infraestructura de almacenamiento en Google Cloud. 
---
= Proporcione permisos de Google Cloud a BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si instaló manualmente el software Connector en su propio host Linux, debe proporcionar BlueXP los permisos que configuró anteriormente. Al proporcionar los permisos, BlueXP podrá gestionar tus datos y la infraestructura de almacenamiento en Google Cloud.

link:task-set-up-permissions-google.html["Aprenda a configurar estos permisos"].

Estos pasos no se aplican si ha implementado el conector directamente desde BlueXP o utilizando gcloud.

.Pasos
. Vaya al portal de Google Cloud y asigne la cuenta de servicio a la instancia de Connector VM.
+
https://["Documentación de Google Cloud: Cambiar la cuenta de servicio y los ámbitos de acceso para una instancia"^]

. Si desea implementar Cloud Volumes ONTAP en otros proyectos, conceda acceso agregando la cuenta de servicio con la función BlueXP a dicho proyecto. Deberá repetir este paso con cada proyecto.


.Resultado
BlueXP ahora tiene los permisos que necesita para realizar acciones en Google Cloud en su nombre.
