---
sidebar: sidebar 
permalink: task-set-up-networking-azure.html 
keywords: azure networking, networking, vnet, subnet, azure region, connections, outbound connections, endpoints, urls, proxy, proxy server 
summary: Configure su red para que Connector pueda gestionar recursos y procesos en su entorno de cloud híbrido. Por ejemplo, debe asegurarse de que las conexiones estén disponibles para las redes de destino y de que el acceso a Internet de salida esté disponible. 
---
= Configure las redes de Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configure su red para que Connector pueda gestionar recursos y procesos en su entorno de cloud híbrido. Por ejemplo, debe asegurarse de que las conexiones estén disponibles para las redes de destino y de que el acceso a Internet de salida esté disponible.



== Vnet y subred

Al crear el conector, debe especificar el vnet y la subred donde debería residir el conector.



== Región de Azure

Si utiliza Cloud Volumes ONTAP, el conector debe desplegarse en la misma región de Azure que los sistemas Cloud Volumes ONTAP que gestiona, o en el https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiones de Azure"^] Para los sistemas Cloud Volumes ONTAP. Este requisito garantiza que se utilice una conexión de enlace privado de Azure entre Cloud Volumes ONTAP y sus cuentas de almacenamiento asociadas.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Conozca cómo Cloud Volumes ONTAP utiliza un enlace privado de Azure"^]



== Conexiones a redes de destino

Un conector requiere una conexión de red a la ubicación en la que tiene previsto crear y administrar entornos de trabajo.



== Acceso a Internet de salida

La ubicación de red en la que implemente el conector debe tener una conexión a Internet saliente. También es necesario acceder a Internet saliente desde su navegador web cuando ponga en marcha Connector desde la consola de BlueXP.



=== Extremos en los que se han contactado desde la consola de BlueXP

A medida que utiliza la consola basada en Web BlueXP que se proporciona a través de la capa SaaS, se pone en contacto con varios extremos para completar las tareas de gestión de datos. Esto incluye los extremos que se ponen en contacto para poner en marcha el conector desde la consola de BlueXP.

link:reference-networking-saas-console.html["Consulte la lista de extremos con los que se ha contactado desde la consola de BlueXP"].



=== Puntos finales contactados durante la instalación manual

Si piensa instalar manualmente el conector en su propio host Linux, el instalador del conector requiere acceso a las siguientes direcciones URL durante el proceso de instalación:

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net


Es posible que el host intente actualizar paquetes de sistema operativo durante la instalación. El host puede ponerse en contacto con diferentes sitios de duplicación para estos paquetes de SO.



=== Puntos finales contactados desde el conector

El conector requiere acceso a Internet saliente para contactar con los siguientes puntos finales con el fin de administrar los recursos y procesos dentro de su entorno de nube pública para las operaciones diarias.

[cols="2*"]
|===
| Puntos finales | Específico 


| \https://management.azure.com
\https://login.microsoftonline.com
\https://blob.core.windows.net
\https://core.windows.net | Para gestionar recursos en regiones públicas de Azure. 


| \https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn
\https://blob.core.chinacloudapi.cn
\https://core.chinacloudapi.cn | Para gestionar recursos en regiones de Azure China. 


| \https://support.netapp.com | Para obtener información sobre licencias y enviar mensajes de AutoSupport al soporte de NetApp. 


 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
Proporcionar funciones y servicios SaaS dentro de BlueXP.


NOTE: El conector se está comunicando actualmente con "cloudmanager.cloud.netapp.com" pero empezará a ponerse en contacto con "api.bluexp.netapp.com" en una próxima versión.



| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net | Para actualizar el conector y sus componentes de Docker. 
|===


== Servidor proxy

Si su organización requiere la implementación de un servidor proxy para todo el tráfico saliente de Internet, obtenga la siguiente información acerca del proxy HTTP o HTTPS:

* Dirección IP
* Credenciales
* Certificado HTTPS




== Puertos

No hay tráfico entrante en el conector, a menos que lo inicie o si el conector se utiliza como proxy para los mensajes AutoSupport.

* HTTP (80) y HTTPS (443) proporcionan acceso a la interfaz de usuario local, que utilizará en raras circunstancias.
* SSH (22) solo es necesario si necesita conectarse al host para solucionar problemas.
* Las conexiones de entrada a través del puerto 3128 son necesarias si implementa sistemas Cloud Volumes ONTAP en una subred en la que no hay una conexión de Internet de salida disponible. Si los sistemas Cloud Volumes ONTAP no tienen una conexión a Internet de salida para enviar mensajes AutoSupport, BlueXP configura automáticamente esos sistemas Cloud Volumes ONTAP para que utilicen un servidor proxy incluido con el conector. El único requisito es asegurarse de que el grupo de seguridad del conector permite conexiones entrantes a través del puerto 3128. Tendrá que abrir este puerto después de desplegar el conector.




== Limitación de dirección IP

Puede haber un conflicto con las direcciones IP en el rango 172. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["Obtenga más información sobre esta limitación"].
