---
sidebar: sidebar 
permalink: task-set-up-permissions-aws.html 
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials 
summary: Configure los permisos en AWS para que pueda implementar Connector con los permisos que necesita para gestionar su infraestructura de datos y almacenamiento. La forma en que configure y proporcione los permisos depende de la opción de instalación que esté planeando utilizar. 
---
= Configure los permisos de AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configure los permisos en AWS para que pueda implementar Connector con los permisos que necesita para gestionar su infraestructura de datos y almacenamiento. La forma en que configure y proporcione los permisos depende de la opción de instalación que esté planeando utilizar.

Puede elegir entre las siguientes opciones de instalación:

* *Instalar desde BlueXP*: Configure los permisos que permiten a BlueXP autenticarse con AWS y desplegar la instancia. BlueXP configura automáticamente los permisos para la instancia de Connector durante la implementación.
+
<<Configure los permisos para crear el conector desde BlueXP,Vea las instrucciones paso a paso>>.

* *Instalar desde AWS Marketplace*: Configurar una función de IAM que puede asociar con la instancia de Connector.
+
<<Configure permisos para el conector cuando ponga en marcha desde AWS Marketplace,Vea las instrucciones paso a paso>>.

* *Instalación manual*: Cree políticas de IAM y conéctelas a una función de IAM o a un usuario de IAM.
+
<<Configure los permisos que se asignarán después de la instalación manual,Vea las instrucciones paso a paso>>.





== Configure los permisos para crear el conector desde BlueXP

BlueXP debe autenticarse con AWS para poder implementar la instancia de Connector en su VPC. Es posible elegir uno de los siguientes métodos de autenticación:

* Deje que BlueXP asuma una función de IAM que tenga los permisos necesarios
* Proporcione una clave secreta y de acceso de AWS para un usuario IAM que tenga los permisos necesarios


Con cualquiera de las dos opciones, el primer paso es crear una política de IAM. Esta directiva sólo contiene los permisos necesarios para iniciar la instancia de Connector en AWS desde BlueXP.

Si es necesario, puede restringir la política de IAM mediante el IAM `Condition` elemento. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["Documentación de AWS: Elemento de condición"^]


TIP: Cuando BlueXP crea el conector, aplica un nuevo conjunto de permisos a la instancia de Connector que habilita los recursos de Connector a AWS.

.Pasos
. Vaya a la consola IAM de AWS.
. Haga clic en *Directivas > Crear directiva*.
. Haga clic en *JSON*.
. Copie y pegue la siguiente política:
+
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}
----
. Haga clic en *Siguiente* y agregue etiquetas, si es necesario.
. Haga clic en *Siguiente* e introduzca un nombre y una descripción.
. Haga clic en *Crear directiva*.
. Adjunte la política a una función de IAM que BlueXP puede asumir o a un usuario de IAM para que pueda proporcionar claves de acceso a BlueXP:
+
** (Opción 1) Configurar una función de IAM que BlueXP puede asumir:
+
... Vaya a la consola AWS IAM de la cuenta de destino.
... En Access Management, haga clic en *roles > Crear función* y siga los pasos para crear la función.
... En *Tipo de entidad de confianza*, seleccione *cuenta de AWS*.
... Seleccione *otra cuenta de AWS* e introduzca el ID de la cuenta de BlueXP SaaS: 952013314444
... Seleccione la directiva que ha creado en la sección anterior.
... Después de crear la función, copie la función ARN para que pueda pegarla en BlueXP al crear el conector.


** (Opción 2) Configurar permisos para un usuario de IAM para que pueda proporcionar claves de acceso a BlueXP:
+
... En la consola AWS IAM, haga clic en *usuarios* y, a continuación, seleccione el nombre de usuario.
... Haga clic en *Agregar permisos > Adjuntar directivas existentes directamente*.
... Seleccione la política que ha creado.
... Haga clic en *Siguiente* y, a continuación, en *Agregar permisos*.
... Asegúrese de disponer de la clave de acceso y la clave secreta para el usuario del IAM.






.Resultado
Ahora debe tener un rol de IAM que tenga los permisos necesarios o un usuario de IAM que tenga los permisos necesarios. Al crear el conector desde BlueXP, puede proporcionar información sobre la función o las claves de acceso.



== Configure permisos para el conector cuando ponga en marcha desde AWS Marketplace

Crear políticas de IAM en AWS y adjuntarlas a un rol de IAM. Al crear el conector desde AWS Marketplace, se le pedirá que seleccione ese rol de IAM.

.Pasos
. En la consola IAM, cree una normativa:
+
.. Haga clic en *Directivas > Crear directiva*.
.. Seleccione *JSON* y copie y pegue el contenido del link:reference-permissions-aws.html["Políticas de IAM para el conector"].
.. Finalice los pasos restantes para crear la directiva.
+
Dependiendo de los servicios de BlueXP que tenga previsto utilizar, puede que necesite crear una segunda política.

+
Para las regiones estándar, los permisos se distribuyen en dos directivas. Son necesarias dos políticas debido a un límite máximo de tamaño de carácter para las políticas gestionadas en AWS.



. En la consola del IAM, cree un rol IAM:
+
.. Haga clic en *roles > Crear rol*.
.. Seleccione *Servicio AWS > EC2*.
.. Agregue permisos asociando las directivas creadas en el paso anterior.
.. Finalice los pasos restantes para crear la función.




.Resultado
Ahora tiene el rol de IAM que se puede asociar a la instancia de EC2 durante la implementación desde AWS Marketplace.



== Configure los permisos que se asignarán después de la instalación manual

Si instala manualmente el software Connector en su propio host Linux en AWS, puede proporcionar permisos de las siguientes formas:

* Opción 1: Crear políticas IAM y asociar las políticas a una función IAM que se puede asociar a la instancia de EC2.
* Opción 2: Proporcione BlueXP con claves de acceso de AWS para un usuario de IAM que tenga los permisos necesarios.


[role="tabbed-block"]
====
.Rol IAM
--
.Pasos
. En la consola IAM, cree una normativa:
+
.. Haga clic en *Directivas > Crear directiva*.
.. Seleccione *JSON* y copie y pegue el contenido del link:reference-permissions-aws.html["Política de IAM para el conector"].
.. Finalice los pasos restantes para crear la directiva.
+
Dependiendo de los servicios de BlueXP que tenga previsto utilizar, puede que necesite crear una segunda política.

+
Para las regiones estándar, los permisos se distribuyen en dos directivas. Son necesarias dos políticas debido a un límite máximo de tamaño de carácter para las políticas gestionadas en AWS. link:reference-permissions-aws.html["Obtenga más información sobre las políticas de IAM para el conector"].



. En la consola del IAM, cree un rol IAM:
+
.. Haga clic en *roles > Crear rol*.
.. Seleccione *Servicio AWS > EC2*.
.. Agregue permisos asociando las directivas creadas en el paso anterior.
.. Finalice los pasos restantes para crear la función.




.Resultado
Ahora tiene la función IAM que puede asociar con la instancia de EC2 después de instalar el conector. link:task-provide-permissions-aws.html["Aprenda a proporcionar estos permisos a BlueXP"].

--
.Clave de acceso de AWS
--
.Pasos
. En la consola IAM, cree una normativa:
+
.. Haga clic en *Directivas > Crear directiva*.
.. Seleccione *JSON* y copie y pegue el contenido del link:reference-permissions-aws.html["Política de IAM para el conector"].
.. Finalice los pasos restantes para crear la directiva.
+
Dependiendo de los servicios de BlueXP que tenga previsto utilizar, puede que necesite crear una segunda política.

+
Para las regiones estándar, los permisos se distribuyen en dos directivas. Son necesarias dos políticas debido a un límite máximo de tamaño de carácter para las políticas gestionadas en AWS. link:reference-permissions-aws.html["Obtenga más información sobre las políticas de IAM para el conector"].



. Adjunte las políticas a un usuario de IAM.
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["Documentación de AWS: Crear roles de IAM"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Documentación de AWS: Adición y eliminación de políticas de IAM"^]


. Asegúrese de que el usuario tiene una clave de acceso que puede agregar a BlueXP después de instalar el conector.


.Resultado
Ahora dispone de un usuario de IAM que tiene los permisos necesarios y una clave de acceso que puede proporcionar a BlueXP. link:task-provide-permissions-aws.html["Aprenda a proporcionar estos permisos a BlueXP"].

--
====