---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: La forma en que inicies sesión en BlueXP depende del modo de puesta en marcha de BlueXP que utilices en tu cuenta. 
---
= Inicie sesión en BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La forma en que inicies sesión en BlueXP depende del modo de puesta en marcha de BlueXP que utilices en tu cuenta.

[role="tabbed-block"]
====
.Modo estándar
--
Después de registrarte en BlueXP, puedes iniciar sesión desde la consola web para empezar a gestionar tu infraestructura de datos y almacenamiento.

.Acerca de esta tarea
Puede iniciar sesión en la consola basada en Web de BlueXP mediante una de las siguientes opciones:

* Sus credenciales existentes del sitio de soporte de NetApp (NSS)
* Un inicio de sesión en el cloud de NetApp con su dirección de correo electrónico y una contraseña
* Una conexión federada
+
Puede utilizar el inicio de sesión único para iniciar sesión con credenciales del directorio corporativo (identidad federada). link:concept-federation.html["Aprenda a usar la federación de identidades con BlueXP"].



.Pasos
. Abra un explorador web y vaya al https://console.bluexp.netapp.com["Consola BlueXP"^]
. En la página *Iniciar sesión*, introduzca la dirección de correo electrónico asociada a su inicio de sesión.
. En función del método de autenticación asociado a su inicio de sesión, se le pedirá que introduzca sus credenciales:
+
** Credenciales de cloud de NetApp: Introduzca su contraseña
** Federated user: Introduzca las credenciales de identidad federadas
** Cuenta del sitio de soporte de NetApp: Introduzca sus credenciales del sitio de soporte de NetApp




.Resultado
Ya ha iniciado sesión y puede empezar a utilizar BlueXP para gestionar su infraestructura multicloud híbrida.

--
.Modo restringido
--
Cuando utilizas BlueXP en modo restringido, tendrás que iniciar sesión en la consola de BlueXP desde la interfaz de usuario que se ejecuta localmente en Connector.

.Acerca de esta tarea
BlueXP permite iniciar sesión con una de las siguientes opciones cuando su cuenta está configurada en modo restringido:

* Un inicio de sesión en el cloud de NetApp con su dirección de correo electrónico y una contraseña
* Una conexión federada
+
Puede utilizar el inicio de sesión único para iniciar sesión con credenciales del directorio corporativo (identidad federada). link:concept-federation.html["Aprenda a usar la federación de identidades con BlueXP"].



.Pasos
. Abra un explorador web e introduzca la siguiente URL:
+
https://_ipaddress_[]

+
_Ipaddress_ puede ser localhost, una dirección IP privada o una dirección IP pública, dependiendo de la configuración del host en el que instaló el conector. Por ejemplo, es posible que necesite introducir una dirección IP privada de un host que tenga una conexión con el host Connector.

. Introduzca su nombre de usuario y contraseña para iniciar sesión.


.Resultado
Ya ha iniciado sesión y puede empezar a utilizar BlueXP para gestionar su infraestructura multicloud híbrida.

--
.Modo privado
--
Cuando utiliza BlueXP en modo privado, tendrá que iniciar sesión en la consola de BlueXP desde la interfaz de usuario que se ejecuta localmente en Connector.

.Acerca de esta tarea
El modo privado admite la gestión de usuarios locales y el acceso. La autenticación no se proporciona a través del servicio en la nube de BlueXP.

.Pasos
. Abra un explorador web e introduzca la siguiente URL:
+
https://_ipaddress_[]

+
_Ipaddress_ puede ser localhost, una dirección IP privada o una dirección IP pública, dependiendo de la configuración del host en el que instaló el conector. Por ejemplo, es posible que necesite introducir una dirección IP privada de un host que tenga una conexión con el host Connector.

. Introduzca su nombre de usuario y contraseña para iniciar sesión.


.Resultado
Ya ha iniciado sesión y puede empezar a utilizar BlueXP para gestionar su infraestructura multicloud híbrida.

--
====