---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: Para instalar manualmente el conector en su propio host Linux, debe revisar los requisitos del host, configurar la red, preparar los permisos de Google Cloud, habilitar las API de Google Cloud, instalar el conector y, a continuación, proporcionar los permisos que preparó. 
---
= Instale manualmente el conector en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede instalar manualmente q Connector en un host Linux que se ejecute en Google Cloud. Para instalar manualmente Connector en su propio host Linux, debe revisar los requisitos del host, configurar la red, preparar los permisos de Google Cloud, habilitar las API, instalar Connector y, a continuación, proporcionar los permisos que preparó.

.Antes de empezar
* Usted debe tener un link:concept-connectors.html["Comprensión de los conectores"].
* Usted debe revisar link:reference-limitations.html["Limitaciones del conector"].




== Paso 1: Revise los requisitos del host

El software del conector debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de puerto, etc.


NOTE: El Conector reserva el rango de UID y GID de 19000 a 19200. Este rango es fijo y no se puede modificar. Si algún software de terceros en su host utiliza UID o GID dentro de este rango, la instalación del Conector fallará. NetApp recomienda usar un host sin software de terceros para evitar conflictos.

Host dedicado:: El conector no es compatible con un host compartido con otras aplicaciones. El host debe ser un host dedicado.
+
--
Host puede ser de cualquier arquitectura que cumpla con los siguientes requisitos de tamaño:

* CPU: 8 núcleos o 8 vCPU
* RAM: 32 GB


--
Hipervisor:: Se requiere un hipervisor nativo o alojado que esté certificado para ejecutar un sistema operativo compatible.
[[podman-versions]]Requisitos del sistema operativo y del contenedor:: BlueXP  admite el conector con los siguientes sistemas operativos cuando se utiliza BlueXP  en modo estándar o en modo restringido. Antes de instalar el conector, se necesita una herramienta de orquestación de contenedores.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| De NetApp | Versiones de OS compatibles | Versiones de conector admitidas | Herramienta de contenedor requerida | SELinux 


 a| 
Red Hat Enterprise Linux
 a| 
9,1 a 9,4

8,6 a 8,10

7,9
 a| 
3.9.40 o posterior con BlueXP  en modo estándar o restringido
 a| 
Podman versión 4.6.1 o 4.9.4

<<podman-configuration,Ver los requisitos de configuración de Podman>>.
 a| 
Compatible con el modo de aplicación o el modo permisivo ^1^



 a| 
Ubuntu
 a| 
24,04 LTS
 a| 
3.9.45 o posterior con BlueXP  en modo estándar o restringido
 a| 
Motor Docker 23.06 a 28.0.0.
 a| 
No admitido



 a| 
22,04 LTS
 a| 
3.9.29 o posterior
 a| 
Motor Docker 23.0.6 a 28.0.0.
 a| 
No admitido

|===
Notas:

. La gestión de sistemas Cloud Volumes ONTAP no es compatible con conectores que tienen SELinux activado en el sistema operativo.
. El conector es compatible con las versiones en inglés de estos sistemas operativos.
. Para RHEL, el host debe estar registrado en Red Hat Subscription Management. Si no está registrado, el host no puede acceder a los repositorios para actualizar el software de terceros necesario durante la instalación del conector.


--
Tipo de máquina de Google Cloud:: Tipo de instancia que cumple los requisitos anteriores de CPU y RAM. Recomendamos n2-standard-8.
+
--
El conector es compatible con Google Cloud en una instancia de máquina virtual con un sistema operativo compatible https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Características de VM blindadas"^]

--
Espacio en disco en /opt:: Debe haber 100 GIB de espacio disponibles
+
--
BlueXP  utiliza `/opt` para instalar el `/opt/application/netapp` directorio y su contenido.

--
Espacio en disco en /var:: Debe haber 20 GiB de espacio disponibles
+
--
BlueXP requiere este espacio en `/var` Porque Docker o Podman están diseñados para crear los contenedores dentro de este directorio. Específicamente, crearán contenedores en el `/var/lib/containers/storage` directorio. Los montajes externos o los enlaces simbólicos no funcionan en este espacio.

--




== Paso 2: Instale Podman o Docker Engine

Dependiendo del sistema operativo, se requiere Podman o Docker Engine antes de instalar el conector.

* Se requiere Podman para Red Hat Enterprise Linux 8 y 9.
+
<<podman-versions,Ver las versiones de Podman que admite BlueXP >>.

* Se requiere Docker Engine para Ubuntu.
+
<<podman-versions,Vea las versiones de Docker Engine compatibles con BlueXP >>.



.Pasos
[role="tabbed-block"]
====
.Podman
--
Siga estos pasos para instalar Podman y configurarlo para cumplir con los siguientes requisitos:

* Habilitar e iniciar el servicio podman.socket
* Instale python3
* Instalar el paquete podman-compose versión 1.0.6
* Agregue podman-compose a la variable de entorno PATH



NOTE: Al usar Podman, ajuste el puerto del servicio aardvark-dns (predeterminado: 53) después de instalar el Conector para evitar conflictos con el puerto DNS del host. Siga las instrucciones para configurar el puerto.

.Pasos
. Elimine el paquete podman-docker si está instalado en el host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instale Podman.
+
Podman está disponible en repositorios oficiales de Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Donde <version> es la versión compatible de Podman que está instalando. <<podman-versions,Ver las versiones de Podman que admite BlueXP >>.

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Donde <version> es la versión compatible de Podman que está instalando. <<podman-versions,Ver las versiones de Podman que admite BlueXP >>.

. Active e inicie el servicio podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instale python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale el paquete de repositorio de EPEL si aún no está disponible en su sistema.
+
Este paso es necesario porque podman-compose está disponible en el repositorio Extra Packages for Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instale el paquete podman-compose 1,0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Con el `dnf install` El comando cumple con los requisitos para agregar podman-compose a la variable de entorno PATH. El comando installation agrega podman-compose a /usr/bin, que ya está incluido en el `secure_path` opción en el host.



--
.Motor Docker
--
Siga la documentación de Docker para instalar Docker Engine.

.Pasos
. https://docs.docker.com/engine/install/["Consulte las instrucciones de instalación de Docker"^]
+
Asegúrese de seguir los pasos para instalar una versión específica de Docker Engine. Al instalar la versión más reciente se instalará una versión de Docker no compatible con BlueXP.

. Compruebe que Docker está habilitado y en ejecución.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Paso 3: Configurar redes

Configure su red para que Connector pueda gestionar recursos y procesos en su entorno de cloud híbrido. Por ejemplo, debe asegurarse de que las conexiones estén disponibles para las redes de destino y de que el acceso a Internet de salida esté disponible.

Conexiones a redes de destino:: Un conector requiere una conexión de red a la ubicación en la que tiene previsto crear y administrar entornos de trabajo. Por ejemplo, la red donde planea crear sistemas Cloud Volumes ONTAP o un sistema de almacenamiento en su entorno local.


Acceso a Internet de salida:: La ubicación de red en la que se despliega el conector debe tener una conexión a Internet saliente para contactar con puntos finales específicos.


Puntos finales contactados desde los equipos cuando se utiliza la consola basada en web de BlueXP :: Los equipos que acceden a la consola de BlueXP  desde un navegador web deben tener la capacidad de contactar con varios puntos finales. Necesitará utilizar la consola BlueXP  para configurar el conector y para utilizar el día a día de BlueXP .
+
--
link:reference-networking-saas-console.html["Prepare las redes para la consola de BlueXP "].

--


Puntos finales contactados durante la instalación manual:: Al instalar manualmente el conector en su propio host Linux, el instalador del conector requiere acceso a las siguientes direcciones URL durante el proceso de instalación:
+
--
* \https://mysupport.netapp.com
* \https://signin.b2c.NetApp.com (este punto final es la URL de CNAME para \https://mysupport.NetApp.com)
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* Para obtener imágenes, el instalador necesita acceder a uno de estos dos conjuntos de puntos finales:
+
** Opción 1 (recomendado):
+
*** \https://bluexpinfraprod.eastus2.data.azurecr.io
*** \https://bluexpinfraprod.azurecr.io


** Opción 2:
+
*** \https://*.blob.core.windows.net
*** \https://cloudmanagerinfraprod.azurecr.io




+
Se recomiendan los puntos finales enumerados en la opción 1 porque son más seguros. Le recomendamos que configure su firewall para permitir los puntos finales enumerados en la opción 1, mientras no permite los puntos finales enumerados en la opción 2. Tenga en cuenta lo siguiente acerca de estos puntos finales:

+
** Los puntos finales enumerados en la opción 1 se admiten a partir de la versión 3.9.47 del conector. No hay compatibilidad con versiones anteriores del conector.
** El conector contacta primero con los puntos finales enumerados en la opción 2. Si no se puede acceder a esos puntos finales, el conector contactará automáticamente con los puntos finales enumerados en la opción 1.
** Los extremos de la opción 1 no son compatibles si utiliza el conector con backup y recuperación de datos de BlueXP  o la protección contra ransomware de BlueXP . En este caso, puede desactivar los puntos finales enumerados en la opción 1, mientras permite los puntos finales enumerados en la opción 2.




Es posible que el host intente actualizar paquetes de sistema operativo durante la instalación. El host puede ponerse en contacto con diferentes sitios de duplicación para estos paquetes de SO.

--


Puntos finales contactados desde el conector:: El conector requiere acceso a Internet saliente para contactar con los siguientes puntos finales con el fin de administrar los recursos y procesos dentro de su entorno de nube pública para las operaciones diarias.
+
--
Tenga en cuenta que los puntos finales que se muestran a continuación son todas las entradas de CNAME.

[cols="2a,1a"]
|===
| Puntos finales | Específico 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Para gestionar recursos en Google Cloud.



 a| 
\https://support.netapp.com
\https://mysupport.netapp.com
 a| 
Para obtener información sobre licencias y enviar mensajes de AutoSupport al soporte de NetApp.



 a| 
\https://\*.api.BlueXP .NetApp.com \https://api.BlueXP .NetApp.com \https://*.cloudmanager.cloud.NetApp.com \https://cloudmanager.cloud.NetApp.com \https://NetApp-cloud-account.auth0.com
 a| 
Proporcionar funciones y servicios SaaS dentro de BlueXP.



 a| 
Elija entre dos conjuntos de puntos finales:

* Opción 1 (recomendado) ^1^
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* Opción 2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
Para obtener imágenes para actualizaciones de Connector.

|===
^1^ Se recomiendan los puntos finales enumerados en la opción 1 porque son más seguros. Le recomendamos que configure su firewall para permitir los puntos finales enumerados en la opción 1, mientras no permite los puntos finales enumerados en la opción 2. Tenga en cuenta lo siguiente acerca de estos puntos finales:

* Los puntos finales enumerados en la opción 1 se admiten a partir de la versión 3.9.47 del conector. No hay compatibilidad con versiones anteriores del conector.
* El conector contacta primero con los puntos finales enumerados en la opción 2. Si no se puede acceder a esos puntos finales, el conector contactará automáticamente con los puntos finales enumerados en la opción 1.
* Los extremos de la opción 1 no son compatibles si utiliza el conector con backup y recuperación de datos de BlueXP  o la protección contra ransomware de BlueXP . En este caso, puede desactivar los puntos finales enumerados en la opción 1, mientras permite los puntos finales enumerados en la opción 2.


--


Servidor proxy:: NetApp admite configuraciones de proxy explícitas y transparentes. Si usa un proxy transparente, solo necesita proporcionar el certificado del servidor proxy. Si usa un proxy explícito, también necesitará la dirección IP y las credenciales.
+
--
* Dirección IP
* Credenciales
* Certificado HTTPS


--


Puertos:: No hay tráfico entrante al conector, a menos que lo inicie o si el conector se utiliza como proxy para enviar mensajes de AutoSupport desde Cloud Volumes ONTAP al soporte de NetApp.
+
--
* HTTP (80) y HTTPS (443) proporcionan acceso a la interfaz de usuario local, que utilizará en raras circunstancias.
* SSH (22) solo es necesario si necesita conectarse al host para solucionar problemas.
* Las conexiones de entrada a través del puerto 3128 son necesarias si implementa sistemas Cloud Volumes ONTAP en una subred en la que no hay una conexión de Internet de salida disponible.
+
Si los sistemas Cloud Volumes ONTAP no tienen una conexión a Internet de salida para enviar mensajes de AutoSupport, BlueXP configura automáticamente esos sistemas para que usen un servidor proxy incluido en el conector. El único requisito es asegurarse de que el grupo de seguridad del conector permite conexiones entrantes a través del puerto 3128. Tendrá que abrir este puerto después de desplegar el conector.



--


Habilite NTP:: Si tienes pensado utilizar la clasificación de BlueXP para analizar tus orígenes de datos corporativos, debes habilitar un servicio de protocolo de tiempo de redes (NTP) tanto en el sistema BlueXP Connector como en el sistema de clasificación de BlueXP para que el tiempo se sincronice entre los sistemas. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Más información sobre la clasificación de BlueXP"^]




== Paso 4: Configurar permisos para el conector

Se necesita una cuenta de servicio de Google Cloud para proporcionar al Connector los permisos que BlueXP necesita para gestionar recursos en Google Cloud. Cuando cree el Connector, deberá asociar esta cuenta de servicio con la VM de Connector.

Es su responsabilidad actualizar el rol personalizado a medida que se agregan nuevos permisos en las versiones posteriores. Si se requieren nuevos permisos, se mostrarán en las notas de la versión.

.Pasos
. Cree un rol personalizado en Google Cloud:
+
.. Cree un archivo YAML que incluya el contenido de link:reference-permissions-gcp.html["Permisos de cuenta de servicio para el conector"].
.. Desde Google Cloud, active Cloud Shell.
.. Cargue el archivo YAML que incluya los permisos necesarios.
.. Cree un rol personalizado mediante `gcloud iam roles create` comando.
+
En el ejemplo siguiente se crea una función denominada "conector" en el nivel de proyecto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentos de Google Cloud: Creación y gestión de roles personalizados"^]



. Cree una cuenta de servicio en Google Cloud y asígnele el rol a la cuenta de servicio:
+
.. En el servicio IAM y Admin, selecciona *Cuentas de servicio > Crear cuenta de servicio*.
.. Ingrese los detalles de la cuenta de servicio y seleccione *Crear y continuar*.
.. Seleccione la función que acaba de crear.
.. Finalice los pasos restantes para crear la función.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentos de Google Cloud: Crear una cuenta de servicio"^]



. Si planea implementar sistemas Cloud Volumes ONTAP en proyectos diferentes a los del proyecto en el que reside el conector, tendrá que proporcionar a la cuenta de servicio del conector acceso a dichos proyectos.
+
Por ejemplo, supongamos que el conector está en el proyecto 1 y que desea crear sistemas Cloud Volumes ONTAP en el proyecto 2. Tendrá que otorgar acceso a la cuenta de servicio en el proyecto 2.

+
.. En el servicio IAM & Admin, seleccione el proyecto de Google Cloud en el que desea crear sistemas Cloud Volumes ONTAP.
.. En la página *IAM*, seleccione *conceder acceso* y proporcione la información necesaria.
+
*** Introduzca el correo electrónico de la cuenta de servicio del conector.
*** Seleccione el rol personalizado del conector.
*** Seleccione *Guardar*.




+
Para obtener información detallada, consulte https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentación de Google Cloud"^]



.Resultado
Se ha configurado la cuenta de servicio del conector VM.



== Paso 5: Configurar permisos de VPC compartidos

Si utiliza un VPC compartido para implementar recursos en un proyecto de servicio, tendrá que preparar los permisos.

Esta tabla es de referencia y el entorno debe reflejar la tabla de permisos cuando se haya completado la configuración de IAM.

.Ver permisos de VPC compartidos
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidad | Creador | Alojadas en | Permisos de proyecto de servicio | Permisos del proyecto host | Específico 


| Cuenta de Google para desplegar el conector | Personalizado | Proyecto de servicio  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Política de despliegue de conectores"]
 a| 
compute.networkUser
| Despliegue del conector en el proyecto de servicio 


| Cuenta de servicio del conector | Personalizado | Proyecto de servicio  a| 
link:reference-permissions-gcp.html["Política de cuenta de servicio de conector"]
| compute.networkUser

deploymentmanager.editor | Implementación y mantenimiento de Cloud Volumes ONTAP y servicios en el proyecto de servicio 


| Cuenta de servicio de Cloud Volumes ONTAP | Personalizado | Proyecto de servicio | storage.admin

miembro: Cuenta de servicio de BlueXP como serviceAccount.user | N.A. | (Opcional) para la organización de datos en niveles y el backup y recuperación de BlueXP 


| Agente de servicio de API de Google | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
compute.networkUser
| Interactúa con las API de Google Cloud en nombre de la implementación. Permite a BlueXP utilizar la red compartida. 


| Cuenta de servicio predeterminada de Google Compute Engine | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
compute.networkUser
| Pone en marcha instancias de Google Cloud e infraestructura de computación en nombre de la puesta en marcha. Permite a BlueXP utilizar la red compartida. 
|===
Notas:

. deploymentmanager.editor sólo es necesario en el proyecto host si no pasa reglas de firewall a la implementación y decide dejar que BlueXP las cree por usted. BlueXP creará una implementación en el proyecto host que contiene la regla de firewall VPC0 si no se especifica ninguna regla.
. Firewall.create y firewall.delete sólo son necesarios si no está pasando reglas de firewall a la implementación y está eligiendo permitir que BlueXP las cree para usted. Estos permisos residen en el archivo .yaml de cuenta de BlueXP. Si va a implementar un par de alta disponibilidad mediante un VPC compartido, estos permisos se utilizarán para crear las reglas de firewall para VPC1, 2 y 3. Para todas las demás implementaciones, estos permisos también se utilizarán para crear reglas para VPC0.
. Para la organización en niveles de los datos, la cuenta del servicio de organización en niveles debe tener el rol serviceAccount.user en la cuenta de servicio, no solo en el nivel del proyecto. Actualmente, si asigna serviceAccount.user en el nivel de proyecto, los permisos no se muestran cuando consulta la cuenta de servicio con getIAMPolicy.


====


== Paso 6: Habilita las API de Google Cloud

Se deben habilitar varias API de Google Cloud antes de poder implementar sistemas de Cloud Volumes ONTAP en Google Cloud.

.Paso
. Habilite las siguientes API de Google Cloud en su proyecto:
+
** API de Cloud Deployment Manager V2
** API de registro en la nube
** API de Cloud Resource Manager
** API del motor de computación
** API de gestión de acceso e identidad (IAM)
** API del servicio de gestión de claves de cloud (KMS)
+
(Solo es obligatorio si piensas utilizar el backup y la recuperación de datos de BlueXP con claves de cifrado gestionadas por el cliente (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentación de Google Cloud: Habilitar API"^]



== Paso 7: Instale el conector

Una vez completados los requisitos previos, puede instalar manualmente el software en su propio host Linux.

.Antes de empezar
Debe tener lo siguiente:

* Privilegios de root para instalar el conector.
* Detalles sobre un servidor proxy, si se necesita un proxy para el acceso a Internet desde el conector.
+
Tiene la opción de configurar un servidor proxy después de la instalación, pero para hacerlo es necesario reiniciar el conector.

* Un certificado firmado por CA, si el servidor proxy utiliza HTTPS o si el proxy es un proxy de interceptación.



NOTE: No se puede configurar un certificado para un servidor proxy transparente al instalar el Conector manualmente. Si necesita configurar un certificado para un servidor proxy transparente, debe usar la Consola de mantenimiento después de la instalación. Obtenga más información sobre el link:reference-connector-maint-console.html["Consola de mantenimiento del conector"].

.Acerca de esta tarea
El instalador disponible en el sitio de soporte de NetApp puede ser una versión anterior. Después de la instalación, el conector se actualiza automáticamente si hay una nueva versión disponible.

.Pasos
. Si las variables del sistema _http_proxy_ o _https_proxy_ están establecidas en el host, elimínelas:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si no elimina estas variables del sistema, la instalación fallará.

. Descargue el software del conector de https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sitio de soporte de NetApp"^]Y, a continuación, cópielo en el host Linux.
+
Debe descargar el instalador "en línea" del conector que se utiliza en su red o en la nube. Hay disponible un instalador "sin conexión" independiente para el conector, pero sólo es compatible con implementaciones en modo privado.

. Asigne permisos para ejecutar el script.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
Donde <version> es la versión del conector que ha descargado.

. Ejecute el script de instalación.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Necesitará agregar la información del proxy si su red requiere uno para acceder a internet. Puede agregar un proxy transparente o explícito. Los parámetros --proxy y --cacert son opcionales y no se le solicitará que los agregue. Si tiene un servidor proxy, deberá introducir los parámetros como se muestra.

+
A continuación se muestra un ejemplo de configuración de un servidor proxy explícito con un certificado firmado por una CA:

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configura el conector para que utilice un servidor proxy HTTP o HTTPS con uno de los siguientes formatos:

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
Tenga en cuenta lo siguiente:

+
*** El usuario puede ser un usuario local o un usuario de dominio.
*** Para un usuario de dominio, debe utilizar el código ASCII para un \ como se muestra anteriormente.
*** BlueXP no admite nombres de usuario ni contraseñas que incluyan el carácter @.
*** Si la contraseña incluye alguno de los siguientes caracteres especiales, debe escapar de ese carácter especial preponiéndolo con una barra diagonal inversa: & O !
+
Por ejemplo:

+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert especifica un certificado firmado por CA que se utilizará para el acceso HTTPS entre el conector y el servidor proxy. Este parámetro es necesario para servidores proxy HTTPS, servidores proxy de interceptación y servidores proxy transparentes.



+
A continuación se muestra un ejemplo de configuración de un servidor proxy transparente. Al configurar un proxy transparente, no es necesario definir el servidor proxy. Solo se agrega un certificado firmado por una CA al host del conector:



+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40 --cacert /tmp/cacert/certificate.cer
----
. Si usó Podman, necesitará ajustar el puerto aardvark-dns.
+
.. SSH a la máquina virtual del conector BlueXP.
.. Abra el archivo podman _/usr/share/containers/containers.conf_ y modifique el puerto seleccionado para el servicio DNS de Aardvark. Por ejemplo, cámbielo a 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicie la máquina virtual del conector.


. Espere a que finalice la instalación.
+
Al final de la instalación, el servicio Connector (occm) se reinicia dos veces si ha especificado un servidor proxy.

. Abra un explorador Web desde un host que tenga una conexión con la máquina virtual Connector e introduzca la siguiente URL:
+
https://_ipaddress_[]

. Después de iniciar sesión, configure el conector:
+
.. Especifique la organización BlueXP  que desea asociar al conector.
.. Escriba un nombre para el sistema.
.. En *¿se está ejecutando en un entorno seguro?* mantener el modo restringido desactivado.
+
Debe mantener desactivado el modo restringido porque estos pasos describen cómo utilizar BlueXP en modo estándar. Sólo debe activar el modo restringido si tiene un entorno seguro y desea desconectar esta cuenta de los servicios de entorno de administración de BlueXP. Si ese es el caso, link:task-quick-start-restricted-mode.html["Siga los pasos para comenzar con BlueXP en modo restringido"].

.. Selecciona *Comenzar*.




Si tienes buckets de Google Cloud Storage en la misma cuenta de Google Cloud en la que creaste el conector, verás que el entorno de trabajo de Google Cloud Storage aparece automáticamente en el lienzo de BlueXP. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["Descubre cómo gestionar Google Cloud Storage desde BlueXP"^]



== Paso 8: Proporcionar permisos a BlueXP

Tienes que proporcionar a BlueXP los permisos de Google Cloud que hayas configurado anteriormente. Al proporcionar los permisos, BlueXP podrá gestionar tus datos y la infraestructura de almacenamiento en Google Cloud.

.Pasos
. Vaya al portal de Google Cloud y asigne la cuenta de servicio a la instancia de Connector VM.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentación de Google Cloud: Cambiar la cuenta de servicio y los ámbitos de acceso para una instancia"^]

. Si quieres gestionar recursos en otros proyectos de Google Cloud, otorga acceso agregando la cuenta de servicio con el rol de BlueXP a ese proyecto. Deberá repetir este paso con cada proyecto.


.Resultado
BlueXP ahora tiene los permisos que necesita para realizar acciones en Google Cloud en su nombre.
