---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: Según las acciones que haya adoptado en BlueXP, quizás tenga credenciales de ONTAP y de NSS del sitio de soporte de NetApp al inicio de sesión de usuario de BlueXP. Puede ver y administrar esas credenciales en BlueXP después de haberlas asociado. Por ejemplo, si cambia la contraseña para estas credenciales, deberá actualizar la contraseña en BlueXP. 
---
= Administre las credenciales asociadas con su inicio de sesión de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En función de las acciones que haya adoptado en BlueXP, quizás tenga credenciales de ONTAP asociadas y credenciales del sitio de soporte de NetApp (NSS) con su inicio de sesión de usuario de BlueXP. Puede ver y administrar esas credenciales en BlueXP después de haberlas asociado. Por ejemplo, si cambia la contraseña para estas credenciales, deberá actualizar la contraseña en BlueXP.



== Credenciales de ONTAP

Los usuarios necesitan credenciales de administrador de ONTAP para descubrir clústeres de ONTAP en BlueXP. Sin embargo, el acceso al administrador del sistema de ONTAP depende de si utiliza o no un conector.

.Sin conector
Los usuarios deben introducir sus credenciales de ONTAP para acceder a ONTAP System Manager del clúster. Los usuarios pueden elegir guardar estas credenciales en BlueXP , lo que significa que no se les pedirá que las introduzcan cada vez. Las credenciales de usuario sólo son visibles para el usuario respectivo y se pueden gestionar desde la página de credenciales de usuario.

.Con un conector
De forma predeterminada, no se solicita a los usuarios que introduzcan sus credenciales de ONTAP para acceder a ONTAP System Manager. Sin embargo, un administrador de BlueXP  (con el rol de administrador de la organización) puede configurar BlueXP  para solicitar a los usuarios que introduzcan sus credenciales de ONTAP. Cuando esta configuración está habilitada, los usuarios deben introducir sus credenciales de ONTAP cada vez.

link:task-ontap-access-connector.html["Leer más."^]



== Credenciales de NSS

Las credenciales de NSS asociadas con tu inicio de sesión de BlueXP permiten el registro de soporte, la gestión de casos y el acceso al asesor digital.

* Cuando accedes a *Soporte > Recursos* y te registras para recibir soporte, se te pedirá que asocies las credenciales de NSS con tu inicio de sesión de BlueXP.
+
Esto registra su organización o cuenta para recibir soporte y activa el derecho a soporte. Solo un usuario en su organización o cuenta de BlueXP  debe asociar una cuenta en el sitio de soporte de NetApp con su inicio de sesión de BlueXP  para registrarse para obtener soporte y activar derechos de soporte. Una vez completado, la página *Recursos* muestra que su cuenta está registrada para soporte.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Aprenda a registrarse para obtener soporte"^]

* Al acceder a *Soporte > Administración de casos*, se le pedirá que introduzca sus credenciales de NSS, si aún no lo ha hecho. Esta página permite crear y gestionar los casos de soporte asociados con su cuenta de NSS y su empresa.
* Al acceder a Digital Advisor en BlueXP, se le pedirá que inicie sesión en Digital Advisor introduciendo sus credenciales de NSS.


Tenga en cuenta lo siguiente sobre la cuenta de NSS asociada con su inicio de sesión de BlueXP:

* La cuenta se gestiona en el nivel de usuario, lo que significa que otros usuarios que inician sesión no la pueden ver.
* Solo puede haber una cuenta de NSS asociada con Digital Advisor y la gestión de casos de soporte, por usuario.
* Si intenta asociar una cuenta del sitio de soporte de NetApp a un entorno de trabajo de Cloud Volumes ONTAP, solo puede elegir entre las cuentas de NSS que se hayan agregado a la organización o cuenta de BlueXP  de la que sea miembro.
+
Las credenciales en el nivel de cuenta de NSS son diferentes de la cuenta de NSS asociada con tu inicio de sesión en BlueXP. Las credenciales de nivel de cuenta de NSS le permiten implementar Cloud Volumes ONTAP con BYOL, registrar sistemas PAYGO y actualizar su software.

+
link:task-adding-nss-accounts.html["Obtenga más información sobre el uso de las credenciales de NSS con su organización o cuenta de BlueXP "].





== Gestione las credenciales de usuario

Para gestionar las credenciales de usuario, actualice el nombre de usuario y la contraseña o elimine las credenciales.

.Pasos
. En la parte superior derecha de la consola de BlueXP, seleccione el icono Configuración y seleccione *credenciales*.
. Seleccione *Credenciales de usuario*.
. Si aún no tiene ninguna cuenta de usuario, puede seleccionar *Añadir credenciales de NSS* para añadir su cuenta del sitio de soporte de NetApp.
. Administre las credenciales existentes eligiendo las siguientes opciones en el menú Acciones:
+
** *Actualizar credenciales*: Actualizar el nombre de usuario y la contraseña de la cuenta.
** *Eliminar credenciales*: Elimina la cuenta asociada a tu cuenta de usuario de BlueXP.




.Resultado
BlueXP actualiza sus credenciales y usted ve los cambios cuando accede al clúster ONTAP, al asesor digital o a la página de Administración de casos.
