---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: BlueXP actualiza automáticamente un conector a la última versión cuando se usa BlueXP en modo estándar o modo restringido. Normalmente, cada mes se lanzan nuevas versiones para introducir nuevas funciones y proporcionar mejoras de estabilidad. Si lo prefiere, puede configurar Connector para extraer actualizaciones de imágenes de un repositorio local. Para implementaciones de modo privado, siempre debe actualizar manualmente el conector usted mismo. 
---
= Gestionar actualizaciones de conectores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando utiliza BlueXP  en modo estándar o en modo restringido, BlueXP  actualiza automáticamente su conector a la última versión, siempre y cuando el conector tenga acceso a Internet saliente para obtener la actualización de software. Si necesita administrar manualmente cuando se actualiza el conector, puede desactivar las actualizaciones automáticas para el modo estándar o el modo restringido.


NOTE: Al ejecutar BlueXP  en modo privado, siempre debe actualizar el conector usted mismo.



== Desactive las actualizaciones automáticas

La desactivación de la actualización automática del conector consta de dos pasos. En primer lugar, debe asegurarse de que su conector actual está en buen estado y actualizado. A continuación, editará un archivo de configuración para desactivar la función de actualización automática.


NOTE: Solo puede desactivar las actualizaciones automáticas si tiene la versión de conector 3.9.48 o superior.



=== Compruebe el estado del conector

Debe verificar que el conector es estable y que todos los contenedores que se ejecutan en la VM del conector están en buen estado y en funcionamiento. Después de desactivar las actualizaciones automáticas, la VM del conector deja de buscar nuevos servicios o paquetes de actualización.

Utilice uno de los siguientes comandos para verificar el conector. Todos los servicios deben tener el estado _Running_. Si no es así, póngase en contacto con el soporte de NetApp antes de deshabilitar la actualización automática.

Docker::
+
--
[source, cli]
----
docker ps -a
----
--
Podman::
+
--
[source, cli]
----
podman ps -a
----
--




=== Desactive la actualización automática del conector

Para deshabilitar las actualizaciones automáticas, establezca el indicador _isUpgradeDisabled_ en el archivo _com/opt/application/NetApp/service-manager-2/config.json_. De forma predeterminada, este indicador se establece en falso y el conector se actualiza automáticamente. Puede definir este indicador en true para desactivar las actualizaciones automáticas.

Para volver a habilitar la actualización automática, siga estos pasos y establezca el indicador _isUpgradeDisabled_ en FALSE.

.Pasos
. Asegúrese de haber verificado que su conector está actualizado y en buen estado.
. Edite el archivo _/opt/application/NetApp/service-manager-2/config.json_ y cambie el valor del indicador _isUpgradeDisabled_ a true como se muestra cerca de la parte inferior de este ejemplo.
+
[source]
----
  "isUpgradeDisabled": true,
----
. Guarde el archivo.
. Reinicie el servicio del gestor de servicios 2 ejecutando el siguiente comando:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----




== Actualice el conector

El conector debe reiniciarse durante el proceso de actualización para que la consola basada en Web no esté disponible durante la actualización.

.Pasos
. Descargue el software del conector de https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sitio de soporte de NetApp"^].
+
Asegúrese de descargar el instalador fuera de línea para redes privadas sin acceso a Internet.

. Copie el instalador en el host Linux.
. Asigne permisos para ejecutar el script.
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-offline-<version>
----
+
Donde <version> es la versión del conector que ha descargado.

. Ejecute el script de instalación:
+
[source, cli]
----
sudo /path/BlueXP-Connector-offline-<version>
----
+
Donde <version> es la versión del conector que ha descargado.

. Una vez finalizada la actualización, puede verificar la versión del conector en *Ayuda > Soporte > conector*.

