= Conector 3.9.52
:allow-uri-read: 




=== Conector 3.9.52

Esta versión del conector BlueXP  incluye mejoras de seguridad menores y correcciones de errores, así como algunas actualizaciones adicionales.

En este momento, la versión 3.9.52 está disponible para modo estándar y modo restringido.



==== Compatibilidad con Docker 27 y Docker 28

Docker 27 y Docker 28 ahora son compatibles con el conector.



==== Cloud Volumes ONTAP

Los nodos de Cloud Volumes ONTAP ya no se apagan cuando el Conector no cumple con las normas o permanece inactivo durante más de 14 días. Cloud Volumes ONTAP sigue enviando mensajes de gestión de eventos cuando pierde el acceso al Conector. Este cambio garantiza que Cloud Volumes ONTAP pueda seguir funcionando incluso si el Conector permanece inactivo durante un período prolongado. No modifica los requisitos de cumplimiento del Conector.



=== Administración de Keystone disponible en BlueXP 

La versión beta para NetApp Keystone en BlueXP  ha añadido acceso a la administración de Keystone. Puede acceder a la página de registro de la versión beta de NetApp Keystone desde la barra de navegación izquierda de BlueXP .



=== Gestión de acceso e identidades (IAM) de BlueXP 



==== Nuevos roles de gestión de almacenamiento

Los roles de administrador de almacenamiento, especialista en estado del sistema y visualizador de almacenamiento están disponibles y se pueden asignar a los usuarios.

Estos roles le permiten administrar quién en su organización puede descubrir y administrar recursos de almacenamiento, así como ver información sobre el estado del almacenamiento y realizar actualizaciones de software.

Estos roles son compatibles para controlar el acceso a los siguientes recursos de almacenamiento:

* Sistemas E-Series
* Sistemas StorageGRID
* Sistemas ONTAP en las instalaciones


También puede utilizar estos roles para controlar el acceso a los siguientes servicios de BlueXP:

* Actualizaciones de software
* Asesor digital
* Resiliencia operativa
* Eficiencia económica
* Sostenibilidad


Se han añadido los siguientes roles:

* *Administrador de almacenamiento*
+
Administrar el estado, la gobernanza y el descubrimiento del almacenamiento de los recursos de la organización. Esta función también puede realizar actualizaciones de software en los recursos de almacenamiento.

* *Especialista en salud del sistema*
+
Administrar el estado y la gobernanza del almacenamiento de los recursos de la organización. Este rol también puede realizar actualizaciones de software en los recursos de almacenamiento. No puede modificar ni eliminar entornos de trabajo.

* *Visor de almacenamiento*
+
Ver información sobre el estado del almacenamiento y datos de gobernanza.

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso."^]


