= Conector 3.9.52
:allow-uri-read: 




=== Conector 3.9.52

Esta versión del conector BlueXP  incluye mejoras de seguridad menores y correcciones de errores, así como algunas actualizaciones adicionales.

En este momento, la versión 3.9.52 está disponible para modo estándar y modo restringido.



==== Compatibilidad con Docker 27 y Docker 28

Docker 27 y Docker 28 ahora son compatibles con el conector.



==== Cloud Volumes ONTAP

Los nodos basados en capacidad de Cloud Volumes ONTAP ya no se apagan cuando el conector no cumple con las normas o permanece inactivo durante más de 14 días. Cloud Volumes ONTAP sigue enviando mensajes de gestión de eventos cuando pierde el acceso al Conector. Este cambio garantiza que Cloud Volumes ONTAP pueda seguir funcionando incluso si el Conector permanece inactivo durante un período prolongado. No modifica los requisitos de cumplimiento del Conector.



=== Administración de Keystone disponible en BlueXP 

La versión beta para NetApp Keystone en BlueXP  ha añadido acceso a la administración de Keystone. Puede acceder a la página de registro de la versión beta de NetApp Keystone desde la barra de navegación izquierda de BlueXP .



=== Gestión de acceso e identidades (IAM) de BlueXP 

Las siguientes nuevas características están disponibles dentro de BlueXP IAM.



==== Autenticación multifactor (MFA) para usuarios locales

Los usuarios locales (no federados ni asociados a una cuenta del sitio de soporte de NetApp) pueden habilitar la autenticación multifactor. Los administradores pueden gestionar la configuración de MFA de los usuarios, como deshabilitarla o eliminarla temporalmente cuando sea necesario.
