= Conector 3.9.53
:allow-uri-read: 




=== Conector 3.9.53

Esta versión del conector BlueXP incluye mejoras de seguridad y correcciones de errores.

La versión 3.9.53 está disponible para el modo estándar y el modo restringido.



=== Alertas de uso de espacio en disco

El Centro de notificaciones ahora incluye alertas sobre el uso del espacio en disco en el Conector. link:task-maintain-connectors.html#monitor-disk-space["Leer más."^]



=== Gestión de acceso e identidades (IAM) de BlueXP 



==== Autenticación multifactor (MFA)

Los usuarios no federados ahora pueden habilitar la autenticación multifactor (MFA) para sus cuentas de BlueXP, lo que mejora la seguridad. Los administradores de BlueXP pueden administrar la configuración de MFA para sus usuarios, restableciéndola o desactivándola según sea necesario. Esto solo es compatible en el modo estándar.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Obtenga información sobre cómo configurar la autenticación multifactor para usted."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["Obtenga información sobre cómo administrar la autenticación multifactor para los usuarios."^]



=== Cargas de trabajo

Ahora puede ver y eliminar las credenciales de Amazon FSx para NetApp ONTAP desde la página Credenciales en BlueXP.
