= 
:allow-uri-read: 


Cree una función y aplíquela a una cuenta de servicio que utilizará para la instancia de Connector VM.

.Pasos
. Cree un rol personalizado en Google Cloud:
+
.. Cree un archivo YAML que incluya los permisos definidos en link:reference-permissions-gcp.html["Política de conectores para Google Cloud"].
.. Desde Google Cloud, active Cloud Shell.
.. Cargue el archivo YAML que incluye los permisos necesarios para el conector.
.. Cree un rol personalizado mediante `gcloud iam roles create` comando.
+
En el ejemplo siguiente se crea una función denominada "conector" en el nivel de proyecto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentos de Google Cloud: Creación y gestión de roles personalizados"^]



. Cree una cuenta de servicio en Google Cloud:
+
.. En el servicio IAM y Admin, selecciona *Cuentas de servicio > Crear cuenta de servicio*.
.. Ingrese los detalles de la cuenta de servicio y seleccione *Crear y continuar*.
.. Seleccione la función que acaba de crear.
.. Finalice los pasos restantes para crear la función.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentos de Google Cloud: Crear una cuenta de servicio"^]





.Resultado
Ahora tiene una cuenta de servicio que puede asignar a la instancia de Connector VM.
